### ISSUE TITLE
[Enhancement] play few midis at once to workaround 16 channel limit, most useful for midi from vgmtrans midi.

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#273] opened 2016-03-12 16:53 UTC
So I just found out the reason why vgmtrans midi doesn't play well on any midi player, some games uses more than 16 channel on a single midi.
the workaround is to split the midi to 2 or 3 or 4 depending on how many channels it needs then making 1 main basmidi stream (to the .mid) then 3 other stream linked to the main stream with BASS_ChannelSetLink (also don't forget about to seek the all the streams :p). this should be enough for 64 channel of midi music.

filename will be
abc.mid
abc.midb
abc.midc
abc.midd

the reason of why not abc.mid.b naming because bassmidi will not use the soundfont abc.sf2 as it looks for abc.mid.sf2 instead.

example of midi http://i.imgur.com/6dpX83h.png

**Comment by droidmjt** [comment] 2016-03-12 18:35
sorry, i don't know how to do this.

**Comment by lybxlpsv** [comment] 2016-03-13 02:44
forgot to say it's the user that splits the midi and all :p.
droidsound-e just need to check if the .midb/.midc/midd exists, and make a bassmidi stream from those midi if the files exists then make BASS_ChannelSetLink so when you play the .mid the other streams will also play.

**Comment by jimbo1qaz** [comment] 2016-03-14 06:39
I don't know of any other midi player that does this.

**Comment by lybxlpsv** [comment] 2016-03-14 07:36
which is why you can't play most of the midi from vgmtrans.
well yeah, except the slightly modified bassmidi player on that pic which you can try here https://dl.dropboxusercontent.com/u/36820280/test_player.rar
to split the midi I use Seikaju, if some tracks uses different channel but same instrument and isn't changed by another midi event later on you can merge it like I did on Chronopolis and HydraMarshes in that rar archive.

**Comment by droidmjt** [comment] 2016-03-15 05:33
I tried this, when I call BASS_ChannelSetLink method, I get error 38 (BASS_ERROR_DECODE), I hope this can be used with DECODE flag.

**Comment by lybxlpsv** [comment] 2016-03-15 06:31
since it's on decode, what happens if you just bass_channelplay every stream at the same time? is there any delay between streams?

**Comment by droidmjt** [comment] 2016-03-19 04:24
i need to involve bassmix to do this, need to rewrite lots of code, if i find time i can add this

**Comment by jimbo1qaz** [comment] 2016-03-19 06:25
Any such "feature" is a hack. The solution is isolating midi tracks from each other, not simultaneous playback of multiple files. Vgmtrans is broken by design.

I would not expect a proprietary Android app to be the first to include such a specific feature. I support splitting midi by track as an option, but kode54 said implementing that in foobar2000 foo_midi plugin was difficult, and didn't do that. Obviously incompatible with hardware synths.

**Comment by lybxlpsv** [comment] 2016-03-21 09:46
I found some SC-88Pro midi having 32 channel (16 port A and 16 port B) on a single file, bassmidi seems to play correctly but most midi editor crashes when opening the file :L

guess time to find some midi editor that support this kind of thing or maybe even more than 32 channel...

**Comment by droidmjt** [comment] 2016-03-22 15:20
so what we gonna do with this?

**Comment by droidmjt** [comment] 2016-03-23 04:55
i'll close this case since it has be come a chaos

**Comment by jimbo1qaz** [comment] 2016-03-23 05:05
Is the code backend too difficult, or did my comment put you off?

**Comment by lybxlpsv** [comment] 2016-03-23 17:03
so i tried the midi isolation thingy without splitting the midi on bassmidi, now ran into tempo issues lol https://youtu.be/ghTSty6KH3I

what i do was check how much track it has (stream is bassmidi streamcreatefile and not going to be played)
while BASS_ChannelGetTags(stream, BASS_TAG_MIDI_TRACK +u) <> nil do u := u +1;

make an array of streams depending on how much track, give the first track that should contains tempo maybe(?) and the track itself on each streams. something like this

`for i:=0 to u do begin
//i have tried sending track 0 on each stream but tempo still not works :(
asdf := BASS_MIDI_StreamGetEvents(fStream,1,0,Nil);
pointer := @track;
asdf := BASS_MIDI_StreamGetEvents(fStream,1,0,pointer);
BASS_MIDI_StreamEvents(dastream[i],BASS_MIDI_EVENTS_STRUCT,pointer,asdf);

asdf := BASS_MIDI_StreamGetEvents(fStream,i,0,Nil);
pointer := @track;
asdf := BASS_MIDI_StreamGetEvents(fStream,i,0,pointer);
BASS_MIDI_StreamEvents(dastream[i],BASS_MIDI_EVENTS_STRUCT,pointer,asdf);
end;`

then play all those individual streams which is maybe isolated tracks.

**Comment by droidmjt** [comment] 2016-03-25 05:41
Once it works without hacks/problems, let me know and i'll find time to rewrite the bassmidi code. Currently i'm busy with something else.

**Comment by droidmjt** [comment] 2016-03-29 15:55
I'll get back to this if/when I have time again.

**Closed by droidmjt** 2016-03-29 15:55 UTC
