### ISSUE TITLE
Bug: Rotation Breaks Scan Display

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#183] opened 2015-08-05 14:56 UTC
Affects ICS, JB, KK, and LP android OSes as far as my testing goes. If at any time during a scan the phone is rotated and the screen reorients, the scan display blanks out or freezes. It still continues scanning but there is no display update going on and no indication of activity. This gets to a point where Android itself detects a hang and requests a wait or forceclose from the user.

**Comment by droidmjt** [comment] 2015-08-05 15:07
bugger, I will add a feature to prevent rotating while scanning.

**Comment by droidmjt** [comment] 2015-08-05 16:10
fixed, will be available in next build

**Comment by Level99OCR** [comment] 2015-08-05 16:24
Awesome, thanks for the quick fix. I hope you're Summer has been relaxing and productive, looking forward to whatever new features you've been working on in secret!

**Comment by droidmjt** [comment] 2015-08-08 13:49
https://www.dropbox.com/s/395yjd2awjysbeg/droidsounde1664_36.apk?dl=0
here we go, as usual, if bugs -> report back :)

**Comment by Level99OCR** [comment] 2015-08-10 20:34
Checking it now. The code does seem to work in that it disables the rotate meaning the scan display doesn't break. Not sure what changed in this release, but maybe the debug is still turned on. ZIP scanning is extremely slow compared to the previous official and beta releases.

Also just FYI I do have a Zenfone 2 now so I am able to test both ARM and x86 android native.  Both ARM and x86 displayed the slow zip.

**Comment by droidmjt** [comment] 2015-08-11 03:22
yeah i noticed the slowness in scanning, it's fixed in the latest build what i'm uploading right now

**Comment by droidmjt** [comment] 2015-08-11 03:24
https://www.dropbox.com/s/4piiaq24ka2s1j7/droidsounde1664_37.apk?dl=0

**Comment by Level99OCR** [comment] 2015-08-11 11:34
Grabbed it, clean install. Still having similar slowness on both architectures. The good news is so far no crashes so I can deal with a slower scan as long as I don't have to babysit my device to make sure the scans complete.

**Comment by droidmjt** [comment] 2015-08-11 11:36
how to reproduce the slow scanning? on what files it happens?

**Comment by Level99OCR** [comment] 2015-08-11 11:41
I'll give you a list once the scan is complete, I'm taking notes now.

It's currently slow on a zip containing all SNES SPC titles. Before, it would take somewhere between 2-5 minutes to scan that entire file. Now, it's at close to 15 minutes and is at 40%.

**Comment by Level99OCR** [comment] 2015-08-11 11:43
C64 zip from HVSC took 4 minutes and 18 seconds compared to sub-one minute times previously.

**Comment by droidmjt** [comment] 2015-08-11 11:45
ah, SPC i can explain, but the latest build _37, scans c64music in less than 20sec here

**Comment by Level99OCR** [comment] 2015-08-12 22:53
Not a big deal. It ended up being my stupidity. I was comparing the C64 x86 scan time vs. the ARM scan time on the other device. The times were pretty evenly spaced out: SPC indeed was slower on both architectures, but comparing the times ARM vs x86 build 37 only had SPC slower end-over-end.

Take your time, and thanks for fixing this bug. Appreciate it!

**Comment by droidmjt** [comment] 2015-08-13 04:00
https://www.dropbox.com/s/pmfim0nnz091gmy/droidsounde1664_38.apk?dl=0
see how this works, it should scan faster, also be aware of bugs :)

**Comment by droidmjt** [comment] 2015-08-15 18:52
https://www.dropbox.com/s/dpfe39lhry997ve/droidsounde1664_39.apk?dl=0

**Comment by droidmjt** [comment] 2015-08-27 07:44
https://www.dropbox.com/s/qcbef1xvqrin627/droidsounde1664_40.apk?dl=0

**Comment by droidmjt** [comment] 2015-08-27 07:47
i'll close this case due to inactivity, reopen if needed.

**Closed by droidmjt** 2015-08-27 07:47 UTC
