### ISSUE TITLE
Settings Reset to Default

### ISSUE THREAD

**Issue by froggestspirit** [droidmjt/Droidsound#466] opened 2018-12-24 15:29 UTC
I've noticed this on android versions 5 or higher (I don't recall it happening on 4.4). When the phone is shut down while music is playing, the settings get reset to the default settings. A way around this is to hit stop on the music and close DSE before turning the phone off, but there's times I've forgotten.

I'm not sure if this might be somewhat related, but it would be a nice feature when shutting down, to have DSE save the currently playing folder/playlist so that it can be resumed when booting back up and pressing play. I generally put large playlists on shuffle, so I don't always get through the playlist and when I boot back up it re-shuffles.

**Comment by droidmjt** [comment] 2018-12-24 16:54
https://www.dropbox.com/s/ygguvaebdgf0mja/droidsounde167_135.apk?dl=1
try this, when you exit the application or turn of the phone, the behaviour will be the same, current path will be saved

**Comment by froggestspirit** [comment] 2018-12-24 17:04
So far it seems like it's doing the same thing. I turned off the phone while playing a playlist on shuffle, both the settings got reset and i wasn't able to resume the playlist. I'll try once more with stopping the playlist before shutting down.

**Comment by droidmjt** [comment] 2018-12-24 17:09
ah, my bad, I forgot to include something

**Comment by stgiga** [comment] 2018-12-24 18:54
Interpolation filters don't need to be included unless you want to give the world a gift.

**Comment by droidmjt** [comment] 2018-12-24 19:00
@stgiga interpolation filters project is not progressing due to the issue I mentioned before, stop mentioning it unless you know how to solve the problem

**Comment by stgiga** [comment] 2018-12-25 17:19
Ok

**Comment by droidmjt** [comment] 2018-12-29 11:48
https://www.dropbox.com/s/b0jowiq0kflyehv/droidsounde167_136.apk?dl=1
try this, after shutdown it should save the active playlist and once the app starts again, the playlist gets automatically opened in PLAYLISTS tab, but the last played song wont be selected.

@stgiga bad news about the kfr lib, it seems to work only with clang, I'm not using clang so I need to find another library

**Comment by froggestspirit** [comment] 2018-12-29 14:32
Here's my tests on the latest version:
-Started playlist, skipped a few songs, stopped music, close DSE, reboot: No changes noticed
-Started playlist, skipped a few songs, close DSE, reboot: No changes noticed
-Started playlist, skipped a few songs, reboot: Settings reset to default
I go to the player screen on reboot and hit play, for all 3 tests, nothing started playing.

**Comment by droidmjt** [comment] 2018-12-29 16:50
https://www.dropbox.com/s/p4m4ets6ywgcv8i/droidsounde167_137.apk?dl=1
try again

**Comment by froggestspirit** [comment] 2018-12-29 16:58
This one still seems to behave as the previous ones with the settings being reset if DSE isn't closed and the play queue not saving

**Comment by droidmjt** [comment] 2018-12-29 17:07
crap, created another bug, ignore those builds

**Comment by droidmjt** [comment] 2018-12-29 18:05
https://www.dropbox.com/s/3qbg197urluofy6/droidsounde167_138.apk?dl=1
lets try again, I tried with my phone and it saved the last path and the last active playlist in playlists tab

**Comment by froggestspirit** [comment] 2018-12-29 19:32
Still no dice on my main music phone. I tried uninstalling before reinstalling. I'm on android 7.1.2
I can try on my call phone later, i think thats on android 8

**Comment by droidmjt** [comment] 2018-12-29 19:44
https://www.dropbox.com/s/xixxpo979efqx1h/droidsounde167_139.apk?dl=1
Here is a small fix, the queue saving is not there. The playlist save works when you are playing songs from a playlist and then exit, if you play a song outside the playlist and exit, it won't save the playlist info and thats it.

**Comment by droidmjt** [comment] 2018-12-29 19:45
If the feature still fails you need to tell exact steps how to reproduce your problem since it works fine for me.

**Comment by froggestspirit** [comment] 2018-12-30 13:52
I'm going to do more testing today. It appears there is a problem with my music phone (im not sure if it's android 7.1.2 or the phone itself) but the settings were saving fine on my main phone (android 8) when rebooting without closing DSE. I found a few roms for android 8 and 9 for my music phone, so I'll try installing those to test with.

**Comment by droidmjt** [comment] 2018-12-30 14:12
What is the brand of your 7.1.2 Android device?

**Comment by droidmjt** [comment] 2018-12-30 14:43
Tried with SGS6 using Android 7.1.2 and it worked fine but on SGS3 using RR 7.1.2 it failed. I think it's because the shut down event is using a different name, for example on HTC devices its something else that ACTION_SHUTDOWN.

**Comment by droidmjt** [comment] 2018-12-30 16:09
all right, I'll close this issue.

**Closed by droidmjt** 2018-12-30 16:09 UTC
