### ISSUE TITLE
Does not support CM11 DSP Equalizer

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#185] opened 2015-09-17 05:17 UTC
Galaxy Nexus CM11...

DSE is detected as a music app, and triggers the settings tray prompt for configuring the equalizer. However, configuring the equalizer has no effect on sound output.

Confirmed in both GPlay and latest test APK.

Why does that happen?

**Comment by droidmjt** [comment] 2015-09-17 06:48
I have no idea really, I have only CyanogenMod 12.1, I hope I can reproduce the problem with it so I could fix it.

**Comment by droidmjt** [comment] 2015-09-17 14:07
it seems that the EQ works only with players that use MediaPlayer instead of AudioTrack or OpenSLES.

**Comment by Level99OCR** [comment] 2015-09-18 15:06
If you're doing EQ work, can you possible include some kind of normalizer/compressor? The per song/per plugin audio settings are fantastic. Normalizing would completely take any edge off of differences between files. Not sure how much extra CPU that would cost as well, just throwing the idea out there.

**Comment by jimbo1qaz** [comment] 2015-09-18 15:59
@Level99OCR Have you heard of ReplayGain?

**Comment by droidmjt** [comment] 2015-09-18 17:03
i'm not expert in this area but i think that replaygain for modern formats would be fast, but for formats like DSF, USF and SID for example might be expensive. code donations welcome :)

**Comment by droidmjt** [comment] 2015-09-18 18:42
or am I completely wrong? hopefully not :)

**Comment by droidmjt** [comment] 2015-09-20 10:26
i'll close this case for now, I have this item on my backlog, once the  feature is ready to be tested i open this case.

**Closed by droidmjt** 2015-09-20 10:26 UTC

**Comment by lybxlpsv** [comment] 2015-12-05 16:18
any possibilities of
plugin --> bass (for compressor,eq, normalizer effect) --> droidsound-e output?

**Comment by droidmjt** [comment] 2015-12-05 16:27
this is scheduled in next official version 1.665, EQ and ReplayGain. No promises when it will be ready.

**Comment by lybxlpsv** [comment] 2015-12-05 16:29
what EQ did you use? other library, BASS_FX_BFX_PEAKEQ (I recommend this one, no distortion at high gain due to peaking eq) or BASS_DX8_PARAMEQ?

**Comment by droidmjt** [comment] 2015-12-05 16:30
a library that works for every plugin, not only BASS.
