### ISSUE TITLE
Crash when loading second file to play

### ISSUE THREAD

**Issue by sam785** [droidmjt/Droidsound#371] opened 2017-06-05 19:32 UTC
Hi,

I have a FiiO X7 digital media player that is running Android 5.1.1 (it's the latest version of Android that's available for this device) and Droidsound-e crashes almost every time I try and load a second song after launching the app.  I'm able to play one song just fine, but whenever I try and load a second song from another file the application will crash.  This happens with every format that doesn't support subsongs - SPC, PSF, MP3, MOD/XM/IT, etc.  If I play a format like NSF with subsongs, I'm able to switch between different subsongs in the same NSF file, but if it loads a different NSF, then it will crash.

I've tried turning accurate data on and off but that didn't make any difference.  I've  also loaded files both on the internal storage and SD card in case it's the storage that's causing it but it still crashes.  No other app on my device is experiencing this behaviour either.

I'm using the latest build that is posted on this site.

Is there any other information I can provide to help troubleshoot this?

**Comment by droidmjt** [comment] 2017-06-06 05:58
logcat log when it crashes

**Comment by sam785** [comment] 2017-06-06 12:56
I have attached the log below...

[droidsound-e_crashlog.txt](https://github.com/droidmjt/Droidsound/files/1055074/droidsound-e_crashlog.txt)

**Comment by droidmjt** [comment] 2017-06-06 16:21
do you have files in droidsound/crashlogs/ folder?

**Comment by droidmjt** [comment] 2017-06-06 16:22
also, are you using the latest version from the main page?

**Comment by droidmjt** [comment] 2017-06-06 16:38
https://www.dropbox.com/s/e2ydtabqanqp5ae/droidsounde167_43.apk?dl=1
try this, probably won't fix it, but at least its the latest version

**Comment by sam785** [comment] 2017-06-06 16:38
I do not have a droidsound/crashlogs folder.  

Yes, I am using the latest version from the main page.

**Comment by droidmjt** [comment] 2017-06-06 16:50
I suspect that the problem is related to your internal sdcard path (/mnt/internal_sd/)

**Comment by droidmjt** [comment] 2017-06-06 16:51
also, when the version i just upload crashes, please send logcat log again

**Comment by sam785** [comment] 2017-06-06 17:01
Here's another dump of the logcat log.  I still don't have a crashloags folder in the droidsound folder..is there an option that I need to enable to enable this?

[droidsound-e_crashlog-2.txt](https://github.com/droidmjt/Droidsound/files/1055842/droidsound-e_crashlog-2.txt)

In this log, I'm loading the files from an external sd card, not the internal storage (I'm loading the same songs from the first log I sent to you).

**Comment by droidmjt** [comment] 2017-06-06 17:03
did you edit the logcat logfile manually?

**Comment by sam785** [comment] 2017-06-06 17:03
I copied and pasted it from Android Studio into a plain text file

**Comment by droidmjt** [comment] 2017-06-06 17:04
i can see only one crash there but it still continues, i'll make another test build

**Comment by droidmjt** [comment] 2017-06-06 17:05
I think you shouldn't use android studio, instead use command line tool

**Comment by sam785** [comment] 2017-06-06 17:06
Sometimes it'll actually play a second song then crash on the third.

Ok...I'll see if I can use it from the command line...I'm not an Android developer and a quick google search pointed me to Android Studio as the easiest way to get the log

**Comment by droidmjt** [comment] 2017-06-06 17:07
Android SDK has adb.exe, 'adb.exe logcat' gives logcat output

**Comment by droidmjt** [comment] 2017-06-06 17:09
actually, no need for me to do another build, the problem is not visible in the logcat log, I'll wait for the new logcat log

**Comment by sam785** [comment] 2017-06-06 17:11
ok...Let me know if this log is helpful.

[logcat.txt](https://github.com/droidmjt/Droidsound/files/1055878/logcat.txt)

**Comment by sam785** [comment] 2017-06-06 17:30
It still crashes...but it seems like every now and then I can load up to 4 files before it crashes.  That's with the MP3 plugin as the only enabled plugin.

Would you like me to send another logcat log?

**Comment by droidmjt** [comment] 2017-06-06 18:04
yes, enable mp3 plugin only, start logcat log and let it crash several times

**Comment by sam785** [comment] 2017-06-06 18:16
Here's the latest log with several crashes...

[logcat.txt](https://github.com/droidmjt/Droidsound/files/1056012/logcat.txt)

**Comment by droidmjt** [comment] 2017-06-06 18:31
disable audiosharpening completely from ActionBar

**Comment by sam785** [comment] 2017-06-06 18:35
I can't find audiosharpening, but I do see Noise Sharpening which is already set to 0.00...

**Comment by droidmjt** [comment] 2017-06-06 18:37
yes noise sharpening, thats correct, how about replaygain?

**Comment by sam785** [comment] 2017-06-06 18:38
Volume source and Volume Mode are disabled for replaygain.  Plugin and Song volumes are set to 0.0

**Comment by droidmjt** [comment] 2017-06-06 18:39
if it still crashes, im out of ideas, its the libc library that crashes somewhere in Player java module :(

**Comment by droidmjt** [comment] 2017-06-06 18:39
and libc is a system library

**Comment by droidmjt** [comment] 2017-06-06 18:40
to get this properly fixed, I need the device to fully debug the problem

**Comment by droidmjt** [comment] 2017-06-06 18:44
has the app ever worked with your device before?

**Comment by sam785** [comment] 2017-06-06 18:45
Damn....I was afraid of that....maybe it'll get fixed in a OS update or something. I can always try reporting this as a bug to FiiO's support.

Anyways, I really appreciate your time in trying to fix this.   This is one of my favourite music players for Android and it works great on my other android device so I'm not completely at a loss here.

**Comment by sam785** [comment] 2017-06-06 18:46
I did recently upgrade from 4.4 Kitkat to 5.1.1 Lolipop so whatever changes which were made there must be causing this.  The odd thing is that Droidsound-e is the only app that's experiencing this crash....

**Comment by droidmjt** [comment] 2017-06-06 18:47
did DS-E work with 4.4 Android in Fiio X7?

**Comment by sam785** [comment] 2017-06-06 18:47
yes it did.  it worked perfectly.  No crashes at all.

**Comment by droidmjt** [comment] 2017-06-06 18:50
some kind of compatibility problem then in my app, sucks.

**Comment by sam785** [comment] 2017-06-06 18:51
I also tried wiping the device after I upgraded the OS in case some leftover things from the upgrade was causing it...

**Comment by sam785** [comment] 2017-06-06 18:52
Yeah...it seems that way...I'll try FiiO's support, if it's a system library that's buggy, maybe they can fix it from their end.

Thanks again for your support.

**Comment by droidmjt** [comment] 2017-06-06 18:52
I'll create one more test build

**Comment by droidmjt** [comment] 2017-06-06 19:23
https://www.dropbox.com/s/h73oj873fflbxta/droidsounde167_44.apk?dl=1
try this

**Comment by sam785** [comment] 2017-06-06 19:30
Still crashes... :(

**Comment by droidmjt** [comment] 2017-06-06 19:31
ah shit, oh well, I'm out of options :(

**Comment by sam785** [comment] 2017-06-06 19:32
No worries.

**Comment by droidmjt** [comment] 2017-06-06 19:44
If you discover something new related to this, leave a msg.

**Closed** 2017-06-06 19:44 UTC
