### ISSUE TITLE
MP3 playback issues with mono files

### ISSUE THREAD

**Issue by Knurek-NC** [droidmjt/Droidsound#460] opened 2018-11-09 19:23 UTC
Sometimes when switching from a stereo MP3 to a mono one, the new song will play at double speed.
This only happens when you have mixed types in a playlist.
If you play the mono one on it's own, there are no issues.
(If you need some mono MP3s to test, free Shovel Knight OST is encoded like that. Available on virt.bandcamp.com)

**Comment by droidmjt** [comment] 2018-11-09 20:34
I'll check it.

**Comment by droidmjt** [comment] 2018-11-09 20:57
I tried with 2 different MP3 songs, one is mono 32000Hz and one is stereo 44100Hz, I was not able to reproduce the problem. You need to provide direct links to songs what I can use and clear instructions how to reproduce the problem.

**Comment by droidmjt** [comment] 2018-11-09 21:15
I suppose you are using the latest version of the app.

**Comment by Knurek-NC** [comment] 2018-11-09 21:57
I've updated to the latest version just in case.
Can't reproduce so far, although previously it's been happening randomly - will let you know if I manage to run into the same problem using the current version.
Thank you.

**Comment by droidmjt** [comment] 2018-11-10 07:50
no problem

**Comment by Knurek-NC** [comment] 2018-11-10 20:56
I've managed to run into this issue again, using the latest version.
Unfortunately, I can't find a way to reliably reproduce it, as after the repeated mono song load, it plays fine.
I guess I'll just reencode the problematic files in the future. :\

**Comment by droidmjt** [comment] 2018-11-11 07:29
well, you could tell how you are playing those files, for example how many files in the playlist? what kind of files in the playlist when the problem happens, only mp3 files? are you using favourites.plist or custom plist? are those entries in your playlist from DB or filesystem? have you changed any settings from the Settings Menu? what android OS version? when the problem appears, is it so that you have been playing only the playlist files or some other files in-between them

**Comment by Knurek-NC** [comment] 2018-11-11 16:05
I'm listening to complete Monotonic netlabel archive (from https://netlabelarchive.org/netlabels/monotonik/), with modules encoded to MP3. That's exactly 1407 files, exclusive MP3s. I've been listening to it for the past few weeks (at work, mostly), the problem happens randomly - like I said, some files just play too fast, no issues after going back/forward in the playlist.
They are stored on an SD card, with Droidsound accessing it through a Filesystem Browser (so, no playlists, as you can only have them with a DB Browser, right?).
Playback is on a Samsung A5 (2016), Android 7.0. I don't think I changed any of the settings, used to have the 'Enable partial wakelock" option enabled (since the playback was choppy for something that required more CPU speed, like 2SF, etc), but nowadays I just encode stuff like that on a PC to MP3s, so I've toggled that option off to save battery life.

**Comment by droidmjt** [comment] 2018-11-11 18:44
I'll close this case for now, if I find the problem, I'll reopen this

**Closed by droidmjt** 2018-11-11 18:44 UTC
