### ISSUE TITLE
Audio fadeout preference not saved (turns off after closing app)

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#278] opened 2016-04-21 05:13 UTC

**Comment by jimbo1qaz** [comment] 2016-04-21 05:18
Possibly fixed in latest program release, after closing, reopening program, and changing fadeout.

**Comment by droidmjt** [comment] 2016-04-21 07:07
I'll check it.

**Comment by droidmjt** [comment] 2016-04-21 20:25
actually, it did save it, but fadeout didnt work if you seeked, now it has been fixed
https://www.dropbox.com/s/bv9y9iym3mvibu9/droidsounde16647_53.apk?dl=0

**Comment by jimbo1qaz** [comment] 2016-04-22 00:17
it seems like the checkbox disappeared again. I'm not sure what causes it. The toolbar/X button is not sufficient to trigger.

**Comment by droidmjt** [comment] 2016-04-22 04:30
>>The toolbar/X button is not sufficient to trigger.
What do you mean? 

I can't reproduce the problem no matter how I try it. If I use the X from ActionBar to terminate it or Force Close it from settings it works in both cases. Tested with various devices including CM13.

**Comment by droidmjt** [comment] 2016-04-22 04:31
Actually, I've got an idea. I'll upload new version later today.

**Comment by droidmjt** [comment] 2016-04-22 06:26
You could try it so that you have no other applications/services running and do nothing else except start the app, enable fade, close the app, start the app again and see if its enabled.

Also the fade switch is no different than any other switch in the settings, if this doesn't work, then others should fail too.

**Comment by droidmjt** [comment] 2016-04-23 14:57
Tested now also with CM11, works normally.

**Comment by droidmjt** [comment] 2016-04-25 05:37
I'll close this since I can't reproduce the problem anyhow.

**Comment by jimbo1qaz** [comment] 2016-06-28 04:13
Still happening on both CM11 and Nexus 5X PureNexus 6.01. It's unpredictable and rare, but definitely happens. I use SPC in 7z and RAR archives, PSF in folders, occasionally USF (not necessary for the bug). I alternate between internal speaker and headphone port. I sometimes use endless repeat.

**Comment by droidmjt** [comment] 2016-06-28 04:21
NOW it is fixed, there was a retard bug, possible left behind accidentally, every time user clicks repeat button, it saves fadeout as disabled state :(

**Comment by droidmjt** [comment] 2016-06-28 04:23
now i remember, i put it there because in endless repeat mode the  fadeout cannot be used, oh well, i refresh the logic now

**Comment by droidmjt** [comment] 2016-06-30 03:35
https://www.dropbox.com/s/wofugue4x25u405/droidsounde16647_77.apk?dl=0

**Comment by jimbo1qaz** [comment] 2016-06-30 05:41
Test...

- enable fadeout
- enable infinite loop
- open psf file
- close DSE
- reopen DSE

Result: Fadeout is still disabled.

If this isn't a result of a simple typo, I suggest writing a "isFadeout"
function = `settings.fadeout && !infiniteLoop` and don't change the
settings directly.

**Comment by droidmjt** [comment] 2016-06-30 06:26
there were 2 places where it saved the fadeout, both have been removed now and it finally works, I tested like you guided.

**Closed** 2016-07-01 19:23 UTC
