### ISSUE TITLE
play / pause Bluetooth

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#205] opened 2015-10-31 15:03 UTC
Hello
There is still a bug here where the program does not register that it has been paused. For example yes it pauses when you turn off Bluetooth speaker but when you look at droidsound it still shows the icon for pause rather than play. As though it hasn't fully registered the pause and still thinks it's playing, this causes a problem when you go to resume play using Bluetooth speaker or stereo control button it sometimes won't resume, and you have to go to your phone and press pause there then play again to get it going again.  Doesn't seem to always happen just sometimes.
Thanks

**Comment by droidmjt** [comment] 2015-10-31 15:28
you could have been a bit more active with this tho

**Comment by droidmjt** [comment] 2015-10-31 16:03
>>  For example yes it pauses when you turn off Bluetooth speaker but when you look at droidsound >> it still shows the icon for pause rather than play.

This is the expected behaviour because if you detach a bluetooth headset, it should pause.

**Comment by filevans** [comment] 2015-10-31 19:20
You havent understood what i have written. And i have been veru active testing it thorougky befite i report anything. It DOES pause fine. There is a bug where it does not show it has paused on the pull down menu. Look what I mean yourself
 And causes a problem when UNPAUSING

**Comment by filevans** [comment] 2015-10-31 19:21
You havent understood what i have written. And i have been very active testing it thoroughly before I report anything. It DOES pause fine. There is a bug where it does not show it has paused on the pull down menu. Look what I mean yourself
And causes a problem when UNPAUSING. Pausing works fine

**Comment by droidmjt** [comment] 2015-10-31 19:47
could you tell me, what pull down menu you mean?

**Comment by droidmjt** [comment] 2015-10-31 19:51
hah, now i found  it, all right, i'll fix it

**Comment by droidmjt** [comment] 2015-10-31 21:11
now it is fixed, i'll upload new binary now

**Comment by droidmjt** [comment] 2015-10-31 21:15
https://www.dropbox.com/s/mb3rcn3dr1ugx8u/droidsounde1664_76.apk?dl=0

**Comment by filevans** [comment] 2015-10-31 23:34
Thanks a lot
 Great. I will test it

**Comment by droidmjt** [comment] 2015-11-01 21:01
https://www.dropbox.com/s/fcli1cxshdyj4wg/droidsounde16645_03.apk?dl=0

**Comment by droidmjt** [comment] 2015-11-07 06:40
Is this working, if yes, close this case.

**Closed** 2015-11-14 07:38 UTC
