### ISSUE TITLE
Adding a folder with zip files to browser causes crash

### ISSUE THREAD

**Issue by sneakernets** [droidmjt/Droidsound#329] opened 2016-09-12 04:35 UTC
Very annoying bug in which adding a folder to the browser with a zip file contained therein, crashes droidsound when it tries to analyze the zip files. Can't use the program because it crashes on opening now. Used the older version in the play store, it now crashes upon viewing my playlists. Deleted data, problem still happens. 

I feel like I shouldn't have upgraded The version I had originally installed on the device, because now, none of them work.

**Comment by sneakernets** [comment] 2016-09-12 04:41
Resolved it by removing dsroot and droidsound folders. Bye bye, playlists...

**Comment by droidmjt** [comment] 2016-09-12 04:41
I was about to say that, backup playlists folders and rename droidsound folder, but ok :)

**Comment by droidmjt** [comment] 2016-09-12 04:43
anyway, the zip problem, could explain what you tried to do so i can fix the bug

**Comment by sneakernets** [comment] 2016-09-12 04:48
I ended up removing the files outright  by extracted them, but I'm not sure why the thing crashed every time it tried to read "Ancient Aliens.zip" in my download folder (long story).

**Comment by droidmjt** [comment] 2016-09-12 10:38
It shouldn't crash even if it read that zip. Could you tell me what filenames you have inside that zip file so i can exclude them?

**Comment by sneakernets** [comment] 2016-09-12 14:29
Here was the file listing:
```
20 GOTO 10.mid
Alien Forest.mid
Basement.mid
Birdsong.mid
Colliding Nebulae.mid
Concentration.mid
Depth Charge.mid
Desk Lamp.mid
Featherfall.mid
Flee.mid
Garden of lost souls.mid
Gigabridge.mid
Goldrush.mid
Hell Jungle.mid
Hypercube.mid
Imaginarium.mid
Long Night.mid
Martian Blues.mid
Moonwalk.mid
Other Side of the Moon.mid
Roof.mid
Space Jiggle.mid
Space Train.mid
Tales of Old.mid
The Demon's Serenade.mid
The Greater Good.mid
The Incessant Flow of Time.mid
The Last Dance.mid
Toejazz.mid
Trapeze.mid
Tribal Dance.mid
Vase.mid
Web of Steel.mid
Welcome to Egypt.mid
Yuletide.mid
```
These are midi files that play normally when extracted from the zip. If you're wondering about the odd names, they're a ripped soundtrack from a video game. 🎮

**Comment by droidmjt** [comment] 2016-09-12 15:12
any chance you could email me the zip file, unless the problem is gone already?

**Comment by sneakernets** [comment] 2016-09-12 17:44
I have a link to the file, one moment: 

http://www.mediafire.com/download/f1ndraf13xx45l4/Ancient_Aliens.zip

**Comment by droidmjt** [comment] 2016-09-12 18:36
tried the zip file, seems to work fine with the latest build

**Comment by droidmjt** [comment] 2016-09-12 19:56
https://www.dropbox.com/s/2ri2tjwptvos3s9/droidsounde167_05.apk?dl=1

**Comment by droidmjt** [comment] 2016-09-12 19:57
if there are no problems, please close this case

**Comment by droidmjt** [comment] 2016-09-13 06:43
Leave a message for unexpected behaviour

**Closed by droidmjt** 2016-09-13 06:43 UTC
