### ISSUE TITLE
Screen Off Audio Stutter

### ISSUE THREAD

**Issue by Incineroar** [droidmjt/Droidsound#343] opened 2017-01-15 07:45 UTC
So a while back I had mentioned how SPC stuttered on my device, however, recently it came to my attention that more audio formats are stuttering now. Below is a list of formats that I'm finding are stuttering on my current device (Samsung S5 Neo w/Android 6.0.1, rooted):

- Super Nintendo SPC (GameMusicEmu)
- KSS (Although it only has done it a very small number of times) (MSXPlug)
- Nintendo DS (vio2sf) (This depends on the game. Pokémon Black/White 2 stutter fairly quickly, while Final Fantasy III doesn't for some period of time)

There may be others, I'll have to double-check all of the songs I have and see what happens.

All of these formats stutter ONLY when the screen on my device turns off. It may play fine for a short time, but then the audio begins to stutter severely, turning on the screen instantly fixes the issue until it turns off again. This doesn't occur on any of my other devices, even the ones that have lowered specs. It also seems to be delayed depending on the settings of the plugin as well. I was told to try a different CPU governor but because of the fact that I have an Exynos processor, and with the lack of willing devs to tackle my device (Both in kernels and ROMs), that's not an option for me.

I'm not entirely sure what's causing it yet, I may try and get a logcat in the coming days and see what it outputs, but I'd like to see if anyone else has this issue and if they've found a solution. I've uninstalled and reinstalled DSE, cleared my cache, rebooted, cleared out background apps, and even did a full reset of my device (By accidentally triggering the FRP lock, whoops!), as well as unrooted, and none of those have fixed the issue.

**Comment by droidmjt** [comment] 2017-01-15 07:58
I have Samsung Galaxy S6 (Android 6.0.1)  and I also experience stuttering when I turn my screen off. This started happening after some specific Android OS version, it wasn't always like this. The stuttering happens even if i enabled partial-wakelock (keep CPU running on max even if screen is off).

Send me a list of songs and I will test with them.

**Comment by Incineroar** [comment] 2017-01-15 08:07
Anything Super Nintendo causes this for me 100% of the time. Chrono Trigger, Final Fantasy 4-6, Sutte Hakkun, all my SPCs seem to cause the stuttering. Depending on the settings of GME, it can either take a few minutes or a few seconds to start this. I was also going to make note of using the wakelock and that it didn't help mitigate the issue any but it slipped my mind.

Also on a slightly related note, GME's NSF playback seems to be bugged as well. Most of my NSFs do not sound correct. I was testing all my formats and found this by complete mistake. Anything VRC6 doesn't work properly, and any songs that make use of noise have that noise track missing (Final Fantasy III, Batman, Super Mario Bros. 3).

**Comment by droidmjt** [comment] 2017-01-15 08:09
There is another NSF player included, switch to that and see how it works.

**Comment by Incineroar** [comment] 2017-01-15 08:11
NSFPlug seems to work properly. Might just use this for now then.

**Comment by droidmjt** [comment] 2017-01-15 09:21
Tested with SGS6 and another low-end Samsung phone (1.2GHz dual-core Android 4.2.2). 

On SGS6 I experienced stuttering only on Pokemon songs and I know c64 sids do this also. SPC files played fine. On the low-end device, none of those formats stuttered. Screen was turned off in both cases.

**Comment by droidmjt** [comment] 2017-01-15 09:57
There is nothing I can do here, please close this case.

**Comment by droidmjt** [comment] 2017-01-15 11:03
leave a msg

**Comment by ItsT3K** [comment] 2017-01-15 15:22
I have a Galaxy S3 Mini and some .miniusf files stutter really badly

**Comment by Incineroar** [comment] 2017-01-15 16:28
@ItsT3K Try enabling HLE for LazyUSF2. I had stuttering on my Ace II X and that setting pretty much completely resolved it.

@droidmjt Apologies for dropping off, I had to head off for the night. I'll see if I can grab a logcat of the event and see what's output there and reopen this when I get that logcat. I'm not sure how verbose DSE is but perhaps I can see what's happening under the hood there, if the OS doesn't report anything at least. I know Modo plays SPCs fine with screen off, perhaps I can ask the author of that app what library he's using. I'll also dig up a set of C64 SIDs and see if the issue replicates, but I'm pretty sure it will.

**Comment by ItsT3K** [comment] 2017-01-15 16:36
HLE enabled and still stuttering

**Comment by droidmjt** [comment] 2017-01-15 17:09
USF format is known to be CPU consuming whether screen is off or not. Nothing I can do there. About SPCs, change interpolation to lowest and try again, I believe MODO uses same library.

**Comment by DavisOlivier** [comment] 2017-01-15 17:15
The stuttering when screen off is caused by minimun cpu clock, try making it higher if youre not in stock rom. I play Sids, spcs, psfs regularly and i dont noticed any stuttering, even when doing intensive multitasking here

Moto G 2013, 1.1Ghz Quad Core 7.1.1

**Comment by Incineroar** [comment] 2017-01-15 17:18
@DavisOlivier I'm thinking it's because of something that Samsung has done specifically. It worked nicely on their Lollipop ROM but it seems to be directly related to Marshmallow itself.

I'd also totally use a non-stock ROM but the only ROMs out there are modified stock ROMs as of now. I haven't checked in a month or so, but I doubt that anyone has done anything custom, although I did once find a device tree for CM13, but I can't find any working builds.

**Comment by DavisOlivier** [comment] 2017-01-15 17:22
@Incineroar Well, maybe you can set the min clock speed to the max one, but it would drain battery quickly of course. You could also search for some custom kernel

**Comment by Incineroar** [comment] 2017-01-15 17:24
@DavisOlivier I'll look into that then, as I don't think I have any custom kernels either. The phone is great but the lack of developer support is quite disappointing.

@droidmjt So I set the SPC interpolation to "None", and it did play for a while, but it began to stutter slightly after about 7 minutes.

**Comment by droidmjt** [comment] 2017-01-15 17:25
crap :(

**Comment by ItsT3K** [comment] 2017-01-15 18:59
I do have Power saver enabled which limits the cpu to 930Mhz (with both
cores active) Maybe I should let all 1200Mhz run?

**Comment by Incineroar** [comment] 2017-01-15 19:17
@ItsT3K That could be it. The USF format is fairly expensive to run so you might have to squeeze all the power you can get out of your device. Changing your CPU scheduler may also help depending on what you set it to.

**Comment by droidmjt** [comment] 2017-01-15 21:47
It looks like MODO is using for SPC some modified version of the library. 
@ItsT3K for USF files you gonna need all the juice your phone has :)

I made a new build that has an option to disable some filter thingy, I'll upload it shortly. I hope that solves the SPC problem.

**Comment by droidmjt** [comment] 2017-01-15 22:01
https://www.dropbox.com/s/g8auh3uc1w1zhy5/droidsounde167_19.apk?dl=1

**Comment by Incineroar** [comment] 2017-01-15 22:03
@droidmjt I'll go and give it a try and I'll absolutely crank up the settings to maximize usage and ensure ideal conditions for the bug and see what happens.

**Comment by droidmjt** [comment] 2017-01-15 22:15
worked with emulator, doesn't seem to work real device here either :( i'll get it fixed

**Comment by droidmjt** [comment] 2017-01-15 22:21
don't use that binary

**Comment by Incineroar** [comment] 2017-01-16 16:19
Did you still want me to get any logcats then?

**Comment by ItsT3K** [comment] 2017-01-16 16:45
So I tried No power saving. Still stutters like crazy. I might try
different devices and see if it works

**Comment by droidmjt** [comment] 2017-01-16 19:20
@ItsT3K S3 Mini has 1.0GHz CPU, even 1.5GHz CPU has trouble playing some USF files. The format is just very CPU consuming and thats it. 

https://www.dropbox.com/s/hekad11du8abfac/droidsounde167_20.apk?dl=1
try this

**Comment by droidmjt** [comment] 2017-01-16 19:22
according to MODO sources, it uses a separate SPC library

**Comment by droidmjt** [comment] 2017-01-16 19:33
Forgot to mention about the new build, disable the SPC filter from settings then try again.

**Comment by DavisOlivier** [comment] 2017-01-16 19:33
So, I tried miniusf/usf playback here and had no stuttering too, screen on/off/multitasking, also put the sample rate to 44000 and im always using viper4android.

I think it may have something to do with samsung's heavy rom

**Comment by droidmjt** [comment] 2017-01-16 19:46
I also tested with SGS3 using CM-13.0-20160410-UNOFFICIAL ROM, default settings, screen turned off SPCs played over 10 mins without stuttering.

**Comment by Incineroar** [comment] 2017-01-17 04:35
I've gone and tried the SPC filter and toggled it. The stuttering still occurs. I'm starting to think that it's some kind of issue with the stock TouchWiz ROM that Samsung has, since everyone here that has top of the line Samsung hardware that has a custom ROM on their device doesn't seem to have this issue.

**Comment by droidmjt** [comment] 2017-01-17 06:38
Try with the latest CM13 ROM, that should help you.

**Comment by Incineroar** [comment] 2017-01-17 06:42
I'm unable to - this is the S5 Neo, not the regular S5. While there is a device tree for CM12 for this device, I have yet to find a built copy that I can flash. Last I know someone was trying to build it, but I haven't heard anything since.

I'd build it myself but I have absolutely no experience in building CyanogenMod, let alone any other ROM.

**Comment by droidmjt** [comment] 2017-01-17 08:30
bad luck :( I also suffer this problem, Sid files cannot play while the screen is turned off

**Comment by DavisOlivier** [comment] 2017-01-17 16:34
Well, you guys can always record the files to wav, but i doubt you'd want that. I also prefer the actual files.

**Comment by Incineroar** [comment] 2017-01-17 20:35
@droidmjt Are you running a custom ROM on the device in which SID files cannot play? I just ran a quick test where I went and disabled AdaptSound and anything Smart Manager through Titanium Backup, then rebooted my phone so they were no longer present in memory, then tested SPC and 2SF files on absolute maximum settings to ensure ideal conditions. It took 6 minutes for the SPC file to begin stuttering this time, so it seems some of what Samsung puts in the OS is causing an incompatibility with the app. I'm going to try toggling some more apps off to continue mitigating the impact that the OS has on DSE and see what else is causing it.

**Comment by droidmjt** [comment] 2017-01-18 06:48
Not using custom ROM. Samsung probably lowered the CPU speed on later OS versions when a device screen is turned off since this didn't happen before. It is not compatibility issue. The only way to solve the SPC problem is to use non-cycle accurate library.

**Comment by droidmjt** [comment] 2017-01-19 06:44
I'll close this case. Leave a msg.

**Closed by droidmjt** 2017-01-19 06:44 UTC

**Comment by Incineroar** [comment] 2017-02-28 21:28
Okay so I finally had a chance to hook my phone up to debug this a bit more, and I finally have some logcat messages that could (or could not) be of any help.

Every single time there is a stutter in the audio, this is output to the log:

AudioFlinger: mixer (0xbdc0000) throttle end: throttle time(XX)

Where XX is a varying value, usually double-digits.

**Comment by droidmjt** [comment] 2017-03-01 08:04
There is nothing I can do here. Like I earlier stated, the stuttering doesn't even happen with some very old and slow phones (1.2GHz) but happens with SGS6. It's the OS problem.

**Comment by Incineroar** [comment] 2017-04-04 06:22
Okay so I managed to find a way to fix the stuttering, however, it was completely on a whim and I could have missed it at time, however, my curiosity managed to help me fix this issue (Specifically the issue was listed in [this post on XDA](https://forum.xda-developers.com/showpost.php?p=39156748&postcount=3)). As you stated it is an OS issue, and that's correct - partially. When Samsung developed the kernel for the device, they made the stupid decision of using a really low setting for the minimum CPU frequency in their Interactive governor to extend battery life. That's great and all for your battery, but boy do apps suffer, DSE in particular when using specific filetypes, and probably numerous other apps as well.

To overcome this issue you will have to be rooted (Or perhaps a custom kernel, but I mean at that rate you might as well just install a custom ROM...), but if you get the app [Device Control](https://play.google.com/store/apps/details?id=org.namelessrom.devicecontrol&hl=en) from the Google Play Store and install it, you can use that to raise the minimum CPU frequency so that DSE isn't starved of processor time and speed. I changed the minimum from the default 400 MHz to 900 MHz, and so far any SPCs I have played have yet to stutter in well over 20 minutes of playback when the screen is off, compared to under a minute before on identical settings (48,000 hz/Sinc interpolation). Of course the values here may depend on the processor and what settings the kernel has for the min/max processor speeds, but this definitely seems to be a very viable fix regardless.

**Comment by droidmjt** [comment] 2017-04-04 09:54
> As you stated it is an OS issue, and that's correct - partially
What's the incorrect part I stated?

**Comment by droidmjt** [comment] 2017-04-04 10:12
Also thanks for your investigation related to this problem :) I really dislike what Samsung did there, even partial wakelock doesn't help in this case.

**Comment by Incineroar** [comment] 2017-04-04 19:40
> What's the incorrect part I stated?
It's Samsung's fault for sure, but it's not the OS that's the problem, it's the _kernel_ that's the problem, as it's what enforces the various CPU settings (Frequencies, scheduler settings, etc). It's for that reason that root is required since you have no other way to adjust the frequencies that the processor will operate at to fix the stuttering issue.

And yeah, it was a dumb thing for Samsung to do. I really wish I could find a better way to fix it, but that'd require knocking on the dev's doors and telling them to stop using such crappy settings.

**Comment by droidmjt** [comment] 2017-04-05 06:02
ah, I see, good thing that there is nothing unclear about this anymore :)
