### ISSUE TITLE
Droidsound reboots tablet when playing gsf or vgm files

### ISSUE THREAD

**Issue by Sir-Sabin** [droidmjt/Droidsound#407] opened 2018-03-06 00:03 UTC
Droidsound reboots tablet when playing gsf or vgm files, it happen on 77 but not on 76, any ideas why this is happens

**Comment by droidmjt** [comment] 2018-03-06 05:38
does it happen with any vgm/gsf file?

**Comment by droidmjt** [comment] 2018-03-06 05:38
explain this scenario in details please

**Comment by Sir-Sabin** [comment] 2018-03-07 02:30
My tablet is a Samsung Tab A on 5.0.2, it rebooted when i try to play Super Chinese 1-2 Advance + SuChi Labyrinth - Youma Gundan no Gyakushuu (2004-06-24)(Yumenosuke Project)(Culture Brain), i think it did it with all

**Comment by droidmjt** [comment] 2018-03-07 05:20
So any VGM or GSF file makes your tablet reboot? Can get you get logcat log?

**Comment by droidmjt** [comment] 2018-03-07 05:23
is it stock ROM what you are using?

**Comment by Sir-Sabin** [comment] 2018-03-07 05:25
I think it's any vgm o4 gsf file and i don't know if i can get logcat files from 5.0 and yes i'm using the stock rom

**Comment by droidmjt** [comment] 2018-03-07 06:49
You can get logcat log with any Android version. Without the log I'm not sure if this can be fixed.

**Comment by Sir-Sabin** [comment] 2018-03-09 05:32
I got it installed, now it won't crash now, I'll post it when it does it

**Comment by droidmjt** [comment] 2018-03-09 05:34
all right

**Comment by droidmjt** [comment] 2018-03-09 16:25
when it crashes and you have the log, leave a msg and I'll reopen this case.

**Comment by Sir-Sabin** [comment] 2018-03-10 02:15
I had it crash on me what type of error msg should i be looking for?

**Comment by droidmjt** [comment] 2018-03-10 06:56
once it crashes, either copy/paste all the available log to a file or let it directly log to a file, then just post the log here

**Comment by Sir-Sabin** [comment] 2018-03-11 04:58
Here's the log file https://www.dropbox.com/s/r91oevgx5cc9zjh/logcat_03-08-2018_22-17-40.txt?dl=0

**Comment by droidmjt** [comment] 2018-03-11 10:01
I couldn't find a single exception from the log file, not one from java or native side. The GSF plugin hasn't changed in this year one bit. In the VGZ plugin there was a minor change between builds 76 and 77. In general if the code would not work as expected it would cause exceptions and the application would crash instead of rebooting your device. 

About the log file, once it crashed, did you restart droidsound-e again? If you did, did you play any files?

**Comment by Sir-Sabin** [comment] 2018-03-11 11:44
Can you find anything in this one i think i posted the wrong one https://www.dropbox.com/s/o8aylyo8s4owq2d/logcat_03-09-2018_21-16-39.txt?dl=0

**Comment by droidmjt** [comment] 2018-03-11 11:58
Even less than before, this log doesn't show any music playing activities.

**Comment by Sir-Sabin** [comment] 2018-03-12 03:57
I cleared the cache in recovery mode to see if it's the cause

**Comment by Sir-Sabin** [comment] 2018-03-12 17:52
It still doing it, here's another log: https://www.dropbox.com/s/gkxmst7jhqm72q3/logcat_03-12-2018_13-38-49.txt?dl=0

**Comment by droidmjt** [comment] 2018-03-13 07:20
Unfortunately there is nothing useful in that log.

**Comment by Sir-Sabin** [comment] 2018-03-16 14:23
Can you check and see if some apps are crashing it to crash? If so They are HP Smart, HP Printing Plugin Google Home and GameEYE

**Comment by droidmjt** [comment] 2018-03-17 07:09
I have no time for that. Are you using those apps?

**Comment by Sir-Sabin** [comment] 2018-03-17 09:29
Yep, i understand you don't have time messing with them

**Comment by droidmjt** [comment] 2018-03-17 09:37
if you are using those apps, uninstall them and see if the crashing goes away

**Comment by droidmjt** [comment] 2018-03-18 07:12
I'll close this case, there is nothing I can do here to help. Leave a msg when you find the root cause.

**Closed by droidmjt** 2018-03-18 07:12 UTC
