### ISSUE TITLE
Music stopping

### ISSUE THREAD

**Issue by JohnHostis** [droidmjt/Droidsound#483] opened 2019-05-21 13:44 UTC
In the last weeks, my Droidsound-E has been stopping music. Everytime, I get between 30 sec and 1 minute before the music stops. When I try to select the app, it boots up like it had been closed, even though it showed the icon on my task bar.

I used to run v. 1.30. After it started doing that, I installed v. 1.50. Nothing changed. So, I uninstall the app, get about 4 days where it works fine, then the issue comes back. I'm stuck in the cycle!

I can't tell if it is linked with an update of the OS.

I have a Galaxy S8.

**Comment by droidmjt** [comment] 2019-05-21 14:30
if possible, do complete fresh install by uninstalling the app and then removing the droidsound folder

**Comment by JohnHostis** [comment] 2019-05-21 15:10
I did not erase the folder before. 'll try that. Meanwhile, the issue happened while these extensions were playing : mp3, brstm, spc, zst and mini2sf.

I did not use any other audio app at the same time.

I'll keep you posted in a few days, since a reinstall resolves it for a while.
Thanks!

**Comment by JohnHostis** [comment] 2019-05-22 02:47
As promised, here are the logs.

[droidsounde_crash_20190515_204948.log](https://github.com/droidmjt/Droidsound/files/3205372/droidsounde_crash_20190515_204948.log)
[droidsounde_crash_20190515_224204.log](https://github.c
[droidsounde_crash_20190516_061932.log](https://github.com/d
[droidsounde_crash_20190516_064034.log](https://git
[droidsounde_crash_20190521_083701.log](https:/
[droidsounde_crash_20190521_083845.log](https://github.com/droidmjt/Droidsound/files/3205377/droidsounde_crash_20190521_083845.log)
/github.com/droidmjt/Droidsound/files/3205376/droidsounde_crash_20190521_083701.log)
hub.com/droidmjt/Droidsound/files/3205375/droidsounde_crash_20190516_064034.log)
roidmjt/Droidsound/files/3205374/droidsounde_crash_20190516_061932.log)
om/droidmjt/Droidsound/files/3205373/droidsounde_crash_20190515_224204.log)

**Comment by droidmjt** [comment] 2019-05-22 04:07
https://www.dropbox.com/s/zgz34mz0p10sloo/droidsounde167_156.apk?dl=1
Try this build if it fixes the crashing. Could you tell me how to reproduce the crash? It looks like it tries to access a file what doesn't exist.

**Comment by JohnHostis** [comment] 2019-05-22 13:29
I tried a clean new installation with the build you provided me this morning. The problem resumed right away. I suppose it was designed to test the problem?

As for what cause the problem, I can't tell. Most of the time, I use an audio jack in my car to listen to my music (which is where it happened the first time). For the purpose of testing, I just let the app run, with or without volume, and check to see if the app closed.

I can't attach logs from my work office, so I'll copy the content here :

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.droidmjt.droidsounde.service.Player.getSongDetails(java.util.Map)' on a null object reference
	at com.droidmjt.droidsounde.service.PlayerService.updateInfo(PlayerService.java:298)
	at com.droidmjt.droidsounde.service.PlayerService.access$600(PlayerService.java:80)
	at com.droidmjt.droidsounde.service.PlayerService$MyHandler.handleMessage(PlayerService.java:540)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
============================
Droidsound-E build: 156
Time: Wed May 22 06:45:49 EDT 2019
CPU: armeabi-v7a
CPU: armeabi
CPU2: arm64-v8a
Fingerprint: samsung/dreamqltevl/dreamqltecan:9/PPR1.180610.011/G950WVLU5CSD5:user/release-keys
CPUFeatures : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
Lang: français
Locale: fr_CA
InternalSD free space: 38220324864
InternalSD path: /storage/emulated/0


Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.droidmjt.droidsounde.service.Player.getSongDetails(java.util.Map)' on a null object reference
	at com.droidmjt.droidsounde.service.PlayerService.updateInfo(PlayerService.java:298)
	at com.droidmjt.droidsounde.service.PlayerService.access$600(PlayerService.java:80)
	at com.droidmjt.droidsounde.service.PlayerService$MyHandler.handleMessage(PlayerService.java:540)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
============================
Droidsound-E build: 156
Time: Wed May 22 08:44:04 EDT 2019
CPU: armeabi-v7a
CPU: armeabi
CPU2: arm64-v8a
Fingerprint: samsung/dreamqltevl/dreamqltecan:9/PPR1.180610.011/G950WVLU5CSD5:user/release-keys
CPUFeatures : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
Lang: français
Locale: fr_CA
InternalSD free space: 38131671040
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment] 2019-05-22 13:34
the song what causes this problem, is it inside an archive? network file? local file? please send me the file what causes this crash

**Comment by droidmjt** [comment] 2019-05-22 14:44
I removed the crashlog since it looked terrible. I saved it locally.

**Comment by droidmjt** [comment] 2019-05-22 14:45
I'll do some testing, I might know what causes the problem.

**Comment by droidmjt** [comment] 2019-05-22 16:15
are you using bluetooth with the app?

**Comment by droidmjt** [comment] 2019-05-22 16:39
Ah, you are using audio jack, ignore my bluetooth question. If possible, send me one of those songs what causes the crash, if you cannot include the link here then please email it to me. I have also SGS8  (Android version 9) and I cannot reproduce the problem.

**Comment by JohnHostis** [comment] 2019-05-22 17:01
I use an audio jack in my car, but I do sometime use Bluetooth to connect my phone with a Bluetooth speaker. I use it on average once or twice a week. 

I'll see to send you some of the music files I know the app crashed while playing.

**Comment by droidmjt** [comment] 2019-05-22 20:09
The songs you sent all played fine. What you could also try is reset preferences and restart the app. Which Android ROM you are using, stock ROM or custom?

**Comment by JohnHostis** [comment] 2019-05-23 02:01
What do you mean by rom? I did not modify my phone nor is it rooted.

I'll try to reset as you suggest.

**Comment by JohnHostis** [comment] 2019-05-23 13:21
I think I may have not fully uninstalled the app last time. Anyway, I tried to follow your advice. I cleaned the cache, cleaned the préférences, deleted my shortcut, uninstalled the app and reinstalled build 156. I got the app running right now and it seems to work fine. I'll keep it on and keep you posted.

Thanks!

**Comment by droidmjt** [comment] 2019-05-23 15:58
good good, I'll close this case for now.

**Closed by droidmjt** 2019-05-23 15:58 UTC
