### ISSUE TITLE
[Enhancement] SFList support and add Opus Library.

### ISSUE THREAD

**Issue by lybxlpsv** [droidmjt/Droidsound#188] opened 2015-10-04 17:13 UTC
Recently hit some limit on soundfont format and need to split up, so sflist support would be great for full GM, GS and XG soundfont in one. or multiple soundfont with different codec as each encoder has it weakness.

Opus because I find opus encoded soundfont sounds good enough at most instruments in 48kbits.

**Comment by droidmjt** [comment] 2015-10-04 17:21
first i need to know what is sflist :) i'll add it if its easy, if not, then it goes to 1.665 version

**Comment by droidmjt** [comment] 2015-10-04 17:37
i think i added opus support long time ago, try it out with the latest unofficial binary

**Comment by lybxlpsv** [comment] 2015-10-04 17:40
sflist is basically just a text file containing

correction.sf2pack
soundfont_gs.sf2pack
r16-viena.sf2pack

then you load the soundfont from top to bottom with array. Shouldn't be too hard.

**Comment by droidmjt** [comment] 2015-10-04 18:04
all right, i'll try to crack some other issues first, I'll add this then.

**Comment by lybxlpsv** [comment] 2015-10-05 17:36
another request, make an option to run BASS_MIDI_StreamEvent MIDI_EVENT_SYSTEM before playback and an option to select MIDI_SYSTEM_DEFAULT, MIDI_SYSTEM_GM1, MIDI_SYSTEM_GM2, MIDI_SYSTEM_GS, MIDI_SYSTEM_XG before playback option would be neat too.

**Comment by droidmjt** [comment] 2015-10-06 05:17
if its not too difficult, why not, i don't want to spend too much time on something very difficult cos the end result is always the same

**Comment by lybxlpsv** [comment] 2015-10-09 18:28
fyi, ian just updated the android bassmidi library so BASS_MIDI_StreamEvent actually works.
http://www.un4seen.com/stuff/bass24-android.zip

**Comment by droidmjt** [comment] 2015-10-10 06:01
great

**Comment by lybxlpsv** [comment] 2015-10-10 06:20
still not perfect tho, in my program I had to make another option called force xg mode because some xg midi still uses gs drumkit for some reason.

```
sf[sfcount].font := BASS_MIDI_FontInit(PChar(dir + 'drumkit.sf2'),BASS_MIDI_FONT_XGDRUMS);
if forcexg = true then begin
sf[sfcount].spreset := -1;
sf[sfcount].sbank := 127;
sf[sfcount].dpreset := -1;
sf[sfcount].dbank := 128;
sf[sfcount].dbanklsb:=0;
end else begin
sf[sfcount].spreset := -1;
sf[sfcount].sbank := -1;
sf[sfcount].dpreset := -1;
sf[sfcount].dbank := 0;
sf[sfcount].dbanklsb:= 0;
end;
```

**Comment by droidmjt** [comment] 2015-10-10 14:52
about the sflist, how would you handle the soundfont volume setting in sflist case? what if you have 3 soundfonts in sflist and one of them is mad loudy and the rest very quiet

**Comment by lybxlpsv** [comment] 2015-10-10 16:07
I don't know about the SFlist specification but if you want to make your own specification I would prefer
<parameter>&<another parameter>&<another parameter>|thefile.sf2pack
parameters ;
spreset
sbank
dpreset
dbank
dbanklsb
volume
xgdrums (if 1, add BASS_MIDI_FONT_XGDRUMS on sf.font parameter)
example :
volume=75&xgdrums=1|soundfont.sf2

**Comment by droidmjt** [comment] 2015-10-10 16:08
well, i just skip the volume setting incase sflist is in use, i have now implemented the sflist option

**Comment by lybxlpsv** [comment] 2015-10-10 16:10
maybe do BASS_MIDI_FONT_XGDRUMS by default on normal soundfonts, It'll probably do no harm on normal GM Soundfont but it's needed for GS/XG drumkit switching

**Comment by droidmjt** [comment] 2015-10-10 17:15
added that.
BASSMIDI.BASS_MIDI_StreamEvent(handle, chan, BASSMIDI.MIDI_EVENT_SYSTEM, param);
which chan this should be applied, all?

**Comment by lybxlpsv** [comment] 2015-10-10 17:43
all channels, and MIDI_EVENT_SYSTEM. MIDI_EVENT_SYSTEMEX is only for if you play midi with BASS_MIDI_NOSYSRESET parameter.

**Comment by droidmjt** [comment] 2015-10-10 21:27
https://www.dropbox.com/s/4pzj8av9b8lovo3/droidsounde1664_57.apk?dl=0
try, most likely not ok but let me know how it goes

**Comment by lybxlpsv** [comment] 2015-10-11 04:06
yeah, sflist doesn't work. the drumkit switching when midi event system xg on droidsound config or sysex from the midi file also doesn't seem to work.

hmm, maybe can I see your bassmidi module source code? (either by e-mail or just post it here, up to you.)

**Comment by droidmjt** [comment] 2015-10-11 05:40
I do this in a loop when i read sf2 filenames from sflist file:

sf = new BASSMIDI.BASS_MIDI_FONT[sflist_files.size()]; 
loop:
int sflist_font = BASSMIDI.BASS_MIDI_FontInit(pathName, BASSMIDI.BASS_MIDI_FONT_XGDRUMS);
sf[x].font = sflist_font;
sf[x].preset = -1; 
sf[x].bank = 0;

int system = (this value comes from settings, 0-4)
for (int x=0;x<channels;x++) {
    BASSMIDI.BASS_MIDI_StreamEvent(songRef, x, BASSMIDI.MIDI_EVENT_SYSTEM, system);
}

**Comment by droidmjt** [comment] 2015-10-11 06:13
i think i found the bug, I call this: BASS_MIDI_StreamSetFonts with last param being 1

**Comment by droidmjt** [comment] 2015-10-11 06:22
https://www.dropbox.com/s/cg1kks9tokdrorc/droidsounde1664_58.apk?dl=0

**Comment by lybxlpsv** [comment] 2015-10-11 06:56
sflist works, sysex commands from midi works. but midi_event_system doesn't work
but BASS_MIDI_StreamEvent MIDI_EVENT_SYSTEM system must be done after BASS_MIDI_StreamCreateFile to work (maybe, I do it like that in my program and it works.)

**Comment by droidmjt** [comment] 2015-10-11 07:00
i set the midi_event_system after the streamcreatefile, nearly at the end, i check more later today

**Comment by lybxlpsv** [comment] 2015-10-11 07:02
wait, nevermind. it's just that you mixed up GS and XG on the settings :p

**Comment by droidmjt** [comment] 2015-10-11 07:11
ah great :) I fix that a bit later, now I need to do something else.. 

I use the following values in Settings:

public static final int MIDI_SYSTEM_DEFAULT=0;
public static final int MIDI_SYSTEM_GM1=1;
public static final int MIDI_SYSTEM_GM2=2;
public static final int MIDI_SYSTEM_XG=3;
public static final int MIDI_SYSTEM_GS=4;

**Comment by droidmjt** [comment] 2015-10-11 09:28
lol, my bad, i misunderstood, in preferences it was mixed, now its fixed, will upload new binary later today :)

**Comment by droidmjt** [comment] 2015-10-11 11:38
is the opus thing also solved?

**Comment by droidmjt** [comment] 2015-10-11 18:16
https://www.dropbox.com/s/i1sxsimx0sxfilh/droidsounde1664_59.apk?dl=0

**Comment by droidmjt** [comment] 2015-10-11 18:20
remove gui.css from droidsound/theme folder after install to get a new style :)

**Comment by lybxlpsv** [comment] 2015-10-11 18:40
opus is working, nice style :)
issue solved.

**Comment by lybxlpsv** [comment] 2015-11-25 01:35
Opus doesn't seem to work now.
http://tempsend.com/4C03AF974D

**Comment by droidmjt** [comment] 2015-11-25 06:35
have you enabled the setting from Settings, there is a switch you need to enable before additional formats work, this is just because of the 4.1.1 library limitation

**Comment by droidmjt** [comment] 2015-11-25 06:37
also the latest beta release is a bit buggy, i'll upload better one today

**Comment by droidmjt** [comment] 2015-11-25 06:42
no, opus thing is broken, i fix it, damnit

**Comment by droidmjt** [comment] 2015-11-25 08:28
now this is getting strange, i haven't touched the bassmidi player code ever since it was fixed last time (october 11). I also double checked with earlier basslibrary and same deal, no sound...is there possibility that the sf2 file is bad or some other setting might interfere it?

**Comment by lybxlpsv** [comment] 2015-11-25 08:51
well I've been using that soundfont on windows bassmidi player and it works fine.
Try load opus plugin with bass plugin load, even though you probably already loaded with those header files.

**Comment by droidmjt** [comment] 2015-11-25 09:03
i tried those soundfont files and i can hear only few instruments, i investigate more later today

**Comment by lybxlpsv** [comment] 2015-11-25 09:16
for the r18-opus48.sf2pack its supposed to not include all instruments as I put the others on ogg aotuv encoder
The drumkit however does include GS and XG drums.

**Comment by droidmjt** [comment] 2015-11-25 17:10
I just packed arachno soundfont using opus mode in soundfont packer and it works just fine.

**Comment by droidmjt** [comment] 2015-11-25 17:11
im not sure what you are expecting of that small opus packed soundfont

**Comment by lybxlpsv** [comment] 2015-11-25 17:53
try the full soundfont here http://tempsend.com/D336E6B193/A0A5/soundfont.zip

**Comment by droidmjt** [comment] 2015-11-25 17:54
all right i try it

**Comment by droidmjt** [comment] 2015-11-25 17:59
plays as usual, i can hear various instruments, drums, guitar, etc etc...using the same FF7 song

**Comment by droidmjt** [comment] 2015-11-25 18:00
what Android OS you have?

**Comment by droidmjt** [comment] 2015-11-25 18:00
oh wait....just a second

**Comment by lybxlpsv** [comment] 2015-11-25 18:06
cm12.1 samsung galaxy grand
just to make sure try just the r18-opus48 and "1-09 Shinra Company XG.mid" or "1-06 Barett's Theme XG.mid"

**Comment by droidmjt** [comment] 2015-11-25 18:06
all right, will do

**Comment by lybxlpsv** [comment] 2015-11-26 04:29
nevermind, just noticed the enable sf2pack aditional libraries switch. I thought its already enabled by default .-.
sorry.

**Comment by lybxlpsv** [comment] 2015-11-26 09:58
now time to wait for this http://www.un4seen.com/forum/?topic=16930.0 to be fixed

**Comment by droidmjt** [comment] 2015-11-26 10:48
lets wait and see :)

**Comment by hoodlum47** [comment] 2015-11-26 23:35
hello, I seem to be having a problem with specifying a patch in a sflist, because if I do MIDI playback breaks but the app doesn't crash. this is what my sflist looks like:

Keppy's Steinway Piano - Grand Piano.sfz
p0,1=0,0|Keppy's Steinway Piano - Bright Piano.sfz
Arachno NO Piano.sf2

Am I doing something wrong or does it have to do with how sflist support was implemented?

**Comment by lybxlpsv** [comment] 2015-11-27 06:25
dont think its implemented. Time for proper implementation maybe?
from foo_midi
p[db#],dp#=[sb#],sp#

**Comment by droidmjt** [comment] 2015-11-27 07:13
i never tried .sfz files, do they work already?
yes i can implement that gibberish thing as long as someone tells me what it is :)

**Comment by lybxlpsv** [comment] 2015-11-27 07:19
yeah, bassmidi library supports it now as long as its not 32bit wave files.
hope u don't kill the old ones :p, well theres already & for separator.
also might wanna add parameter "lsb=#" for dbanklsb

**Comment by droidmjt** [comment] 2015-11-27 08:32
doesn't matter, i try to hack something

**Comment by droidmjt** [comment] 2015-11-27 16:32
is the sflist format documented somewhere?

**Comment by hoodlum47** [comment] 2015-11-27 16:36
I actually tried to find something like that myself since I'm new to the format but came up empty.

**Comment by lybxlpsv** [comment] 2015-11-27 16:42
separator is "&" according to most sflist players

**Comment by kode54** [comment] 2015-11-28 02:04
Ian was supposed to work on a standard sflist parser, so I could eliminate the ugly C++ code that I wrote for that purpose, as well as some other ugly C++ code I use in a completely different project for the same purpose.

My parser is still missing support for per-handle gain overrides, which are essential for some people to amplify or attenuate specific instruments.

**Comment by droidmjt** [comment] 2015-11-28 06:48
I get this fixed now.

**Comment by droidmjt** [comment] 2015-11-28 10:20
p1,0=0,0&vol=0.7&lsb=1|gs.sf2pack
is that format OK ?

**Comment by lybxlpsv** [comment] 2015-11-28 10:23
yeah, that should be ok.

**Comment by droidmjt** [comment] 2015-11-28 17:32
https://www.dropbox.com/s/f1vmixlhztmte89/droidsounde16647_04.apk?dl=0
please test, if it works, close this case

**Comment by lybxlpsv** [comment] 2015-11-28 19:57
i've tried this which should force xg drumkit but it doesn't seem to work
p128,-1=127,-1|r18-drumkit.sf2pack

**Comment by droidmjt** [comment] 2015-11-28 19:58
its because of the -1 thing, i fix it

**Comment by droidmjt** [comment] 2015-11-29 04:52
uploading new binary...stay tuned

**Comment by droidmjt** [comment] 2015-11-29 04:54
https://www.dropbox.com/s/36tdnx1oajzejf3/droidsounde16647_06.apk?dl=0

**Comment by lybxlpsv** [comment] 2015-11-29 09:07
working fine, haven't tried sfz yet.
btw ian has fixed "file seeking issue related to the way that BASSMIDI feeds the file data to the decoder", now to wait for updated android library. or have you gotten the updated library? (timestamp is 27 november on the windows ones)

**Comment by droidmjt** [comment] 2015-11-29 09:08
there is no android version yet and there is another bug also he needs to fix, lets wait for that :)

**Comment by lybxlpsv** [comment] 2015-11-30 16:23
updated: 30 Nov '15 http://www.un4seen.com/stuff/bass24-android.zip

**Comment by droidmjt** [comment] 2015-11-30 16:49
its not fixed, see the other issue about the songlength :(

**Comment by droidmjt** [comment] 2015-11-30 17:25
jetaudio claims its 4:14, android own music player claims its 1:26:22 (lol)

**Comment by droidmjt** [comment] 2015-11-30 17:41
https://www.dropbox.com/s/f57pcp2j7m61jfy/droidsounde16647_07.apk?dl=0

**Comment by droidmjt** [comment] 2015-11-30 20:57
if the initial problem is solved close this case.

**Comment by lybxlpsv** [comment] 2015-12-01 09:43
its works, last request for sflist (hopefully :p) I think spliting the soundfont to lsb is a bad idea (yamaha xg has quite alot of lsb banks which alot of when creating the soundfont :/) so can I has this paramter for sflist?
lsb=1 for lsb mode

if lsb mode you do this when you load the soundfont

```
i := 0;
while i < 127 do begin
sf[sfcount].font := BASS_MIDI_FontInit(soundfont,BASS_MIDI_FONT_XGDRUMS);
sf[sfcount].spreset := -1;
sf[sfcount].sbank := i;
sf[sfcount].dpreset := -1;
sf[sfcount].dbank := 0;
sf[sfcount].dbanklsb := i;
sfcount := sfcount + 1;
i := i + 1;
end;
```

**Comment by droidmjt** [comment] 2015-12-01 15:49
all right

**Comment by droidmjt** [comment] 2015-12-01 17:37
about your request, what if i use a patch that needs dbank while your code just sets it always to zero? also same for sbank. Is there some error in the looping, what if sf[] array size is just 2? maybe something missing there? :)

**Comment by lybxlpsv** [comment] 2015-12-01 17:59
then that's what dbanklsb parameter for, you gotta make another soundfont file if the instruments require both msb and lsb (not much patches uses that, hopefully.)
about sf array size, well I made mine 10000 on my program :P
maybe add +129 to sf array size if lsb parameter is detected maybe?

**Comment by lybxlpsv** [comment] 2015-12-02 16:08
incase you are wondering about the usage of this parameter heres the placeholder soundfont or wanted to test stuff around
http://dl.lybxlpsv.com/files/dropzone/lsbtest.sf2pack

https://www.youtube.com/watch?v=X5RVnoqG1Nw

**Comment by droidmjt** [comment] 2015-12-02 17:14
it looks a bit spooky :)

**Comment by lybxlpsv** [comment] 2015-12-02 17:35
yeah, especially on ram usage. it takes 50-100mb with nothing playing and 100-120mb when playing on such a small soundfont.

**Comment by lybxlpsv** [comment] 2015-12-03 18:36
alright, Ian has found the cause of the weirdly high ram usage when doing lsb stuff.
he says probably tomorrow, hopefully that midi speed bug also fixed

**Comment by droidmjt** [comment] 2015-12-04 18:48
crap no new bassmidi today, monday earliest

**Comment by lybxlpsv** [comment] 2015-12-04 20:51
yeah, atleast the windows ones is fixed for both lsb memory leak and tempo bug.

**Comment by droidmjt** [comment] 2015-12-23 07:36
i := 0;
while i < 127 do begin
sf[sfcount].font := BASS_MIDI_FontInit(soundfont,BASS_MIDI_FONT_XGDRUMS);
sf[sfcount].spreset := -1;
sf[sfcount].sbank := i;
sf[sfcount].dpreset := -1;
sf[sfcount].dbank := 0;
sf[sfcount].dbanklsb := i;
sfcount := sfcount + 1;
i := i + 1;
end;

that loop doesn't make sense, can i see the full code please? what if I have just 1 soundfont file in sflist that uses the lsb flag?

**Comment by droidmjt** [comment] 2015-12-23 07:42
for (int z = 0; z < 127; z++)
{
        sf[x].font = sflist_font;
	sf[x].spreset = -1;
	sf[x].sbank = z;
	sf[x].dpreset = -1;
	sf[x].dbank = 0;
	sf[x].dbanklsb = z;
}

would this work?

**Comment by droidmjt** [comment] 2015-12-23 07:54
ah i need to also create bigger SF array, i see

**Comment by droidmjt** [comment] 2015-12-23 08:00
what if i have 5 soundfonts that each uses the LSB flag? make the SF array 5 * 129?

**Comment by droidmjt** [comment] 2015-12-23 08:09
all right, please give me an example sflist file so i test this

**Comment by lybxlpsv** [comment] 2015-12-23 16:42
http://dl.lybxlpsv.com/files/dropzone/test.zip
also included test midi

**Comment by droidmjt** [comment] 2015-12-23 17:18
all right, will test

**Comment by droidmjt** [comment] 2015-12-23 18:28
would it be possible for you to dump me the sf array contents, sfcount is 265 when it has loaded all the fonts, is that correct?

**Comment by droidmjt** [comment] 2015-12-23 18:30
for (int z = 0; z < 128; z++)
{
	sf[sfcount].font = sflist_font;
	sf[sfcount].spreset = -1;
	sf[sfcount].sbank = z;
	sf[sfcount].dpreset = -1;
	sf[sfcount].dbank = 0;
	sf[sfcount].dbanklsb = z;
	BASSMIDI.BASS_MIDI_FontSetVolume(sflist_font, volume);
	sfcount += 1;
}

**Comment by droidmjt** [comment] 2015-12-23 18:41
lol, now it works, i had to enable additional libs :)

**Comment by droidmjt** [comment] 2015-12-23 22:54
https://www.dropbox.com/s/u1ythy8f5nnob7z/droidsounde16647_10.apk?dl=0

**Comment by droidmjt** [comment] 2015-12-25 09:55
I'll close this case since I think it works as expected now, we can reopen this case if the problem is still there

**Closed by droidmjt** 2015-12-25 09:55 UTC
