### ISSUE TITLE
Bizarre sound error on MP3 with headphones

### ISSUE THREAD

**Issue by Galindorf** [droidmjt/Droidsound#379] opened 2017-07-04 02:33 UTC
I was testing a new pair of earbuds (JVC HAFR37V Marshmallow Earbuds with Mic) and while I had no problems listening to a chiptune, when I started a (compressed zip)MP3 file I got a rushing static so loud in my left ear I had to yank out the earbud, while the right ear had a slow, quiet, extremely creepy tone. Turning the volume all the way down had no effect on the sound level. Hitting 'stop' took about seven seconds to actually stop the sound. 

Thinking something was wrong with Droidsound, I hit play with the earbuds detached and the file continued playing with perfect sound. I then quit Droidsound, cleared the cache, and restarted my phone. Here's where it gets stranger.

If I start an MP3 song without the headphones plugged in, it plays just fine. If I plug the headphones in *while* the song is playing, it continues to play perfectly through the headphones (although the volume was pushed to zero and I had to turn it back up). If I stop the song and restart it with the headphones plugged in, the loud hiss in the right ear, and creepy tone in the left begin again. I also noticed that the time does not advance on the song, and then the sound cuts out altogether with a crackle on the phone speaker (although the headphones are plugged in). If I run a chiptune (tested SPC, MINGSF, NSF, MINIDSF) everything works fine (minus a couple of file types I'm having trouble playing, but that's another issue). 

I tested this with three pairs of headphones, my JVC HAFR37V Marshmallow Earbuds with Mic, a second pair of the same, and the default Samsung headphones. My bluetooth speaker was unaffected, and playing over the phone's native speaker was unaffected.

Further testing: 
Samsung Adapt Sound On: hissing issue
Samsung Adapt Sound Off: same
Samsung built-in-phone equalizer Custom setting: Hissing Issue
Samsung built-in-phone equalizer Normal(flat): Hissing Issue
Droidsound Noise Sharpening 4.16: Hissing
Droidsound Noise Sharpening 0: hissing

Particulars:
Droidsound-E v1.67
Galaxy Note 5
SM-N920T
Android 7.0

Zipped MP3 archive

**Comment by droidmjt** [comment] 2017-07-04 04:50
Send me the MP3 what causes the problem, otherwise I cannot investigate the problem.

**Comment by droidmjt** [comment] 2017-07-04 04:54
Does it happen with any MP3 ?

**Comment by Galindorf** [comment] 2017-07-04 05:28
yeah, it has happend with all the MP3's I have tried on my phone (some in .ZIP archive, some in .7z archive) 

I'm very confused by this, as I am pretty sure I was able to listen to them via headphone before. The only thing I can think of that I installed a program called Music Volume EQ + Bass Booster, so I deleted its data and uninstalled it, restarted my phone. Alas, no difference. 

I can tell you that sometimes, the program hangs on the MP3 and the timer goes up by 1 second, goes no further, and THEN begins the hissing/garbldegook. It appears to be using the BASS plugin.

**Comment by droidmjt** [comment] 2017-07-06 05:31
Just incase could you send me one of those MP3 files what causes trouble ?

**Comment by droidmjt** [comment] 2017-07-08 11:23
I'll close this case, once you send me one of those MP3 what gives trouble I'll reopen this.

**Comment by Galindorf** [comment] 2017-07-08 22:56
no problem mate, been crazy busy. I hope to have it for you this weekend

**Comment by Galindorf** [comment] 2017-07-09 19:20
OK, here is a link to the .zip file I am using for one of the albums that gives me trouble. 

https://drive.google.com/open?id=0B7wZqYH68WV-ZUwtV3E0TE9zTEU

**Comment by droidmjt** [comment] 2017-07-09 19:45
I was able to reproduce the problem now, damn it, this is the craziest effect ever. It won't even go away if I restart the application. I was playing those songs you sent just fine, then all of sudden, left speaker started outputting mad static.

**Comment by droidmjt** [comment] 2017-07-09 19:47
I got this behaviour using Android 7.0 on SGS6. I will try now with my other phone also with Android 7.0

**Comment by droidmjt** [comment] 2017-07-09 19:49
Unplugged my headphones and it works again, the plugged headphones back and back to static. If I cannot reproduce the problem with my newer device I dare to bet that this is another screwup by samsung again.

**Comment by Galindorf** [comment] 2017-07-09 19:50
Ahh, suck. Yeah OK, I was wondering what the heck? The error is so *weird* and very specific. Like I said, there's no problem on the phone's speaker and no problem over bluetooth... I would love to know the science behind this one. It was like I was channeling satan in one ear and the mad static on the other, no matter what the volume level is

**Comment by droidmjt** [comment] 2017-07-09 19:53
I don't know what is the magic behind this. I let the songs run now and see how it goes. This shit is from twilight zone.

**Comment by droidmjt** [comment] 2017-07-09 20:14
ok, I found something, in Settings -> Misc -> Accurate data, if i disable that, the static goes away. The odd thing is that in my newer phone I was using the same feature and no problems.

**Comment by Galindorf** [comment] 2017-07-09 20:27
Success! I disabled the Accurate Data, and it's working again (so far). Glory Be!

...Apparently "accurate data" is... Beelzebub?

**Comment by droidmjt** [comment] 2017-07-09 20:39
I don't think the 'accurate data' is infernal at all since it works fine with BlueTooth. If it would be BASS library's fault, this problem would happen whether user has headphones (BT/cable) or not.

**Closed by droidmjt** 2017-07-09 20:39 UTC

**Comment by droidmjt** [comment] 2017-07-09 20:45
To wrap this up, on my SGS8 (android 7.0) this never happened, used headphones with cable and accurate data but it happens ONLY with SGS6 (android 7.0) when headphones are plugged in and accurate data is enabled. I dare to say its a bug in the android 7.0 for older samsung devices from 2015.

**Comment by droidmjt** [comment] 2017-07-09 21:14
It happens also with another plugin, OpenMPT, and ONLY when accurate data (Float sample data) is enabled and headphones are plugged in (with cable). Samsung's screw up, shit.
