### ISSUE TITLE
It crashes when i play from my own FTP and it doesn't save the FTP link

### ISSUE THREAD

**Issue by Andr20** [droidmjt/Droidsound#261] opened 2016-01-25 17:20 UTC
Hi!
My problem is:
when i select some song from my own FTP droidsound it crashes, the other problem is when i try to add some FTP link with user and password and i give the ok droidsound it doesn't save it, i tryed many ways but it doesn't seem to work, those problems starded from the version 1.664 and at the moment i am back to the version 1.663
P.S. : i am able to log into my FTP SERVER because i saved the file contained in dsroot and created in one old version of Droidsound 1.663

**Comment by droidmjt** [comment] 2016-01-25 17:27
Hello,
i need crashlog before i can anything. 

Get this version:
https://www.dropbox.com/s/k4aqzwyw7jzdb5d/droidsounde16647_35.apk?dl=0

Let me know how it goes.

**Comment by Andr20** [comment] 2016-01-25 17:36
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException
	at com.droidmjt.droidsounde.plugins.FFMPlugin.load(FFMPlugin.java:196)
	at com.droidmjt.droidsounde.service.Player.startSong(Player.java:684)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1225)
	at java.lang.Thread.run(Thread.java:841)
============================
Droidsound-E version: 39
Droidsound-E build: 30
Time: Mon Jan 25 18:32:56 CET 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: Huawei/Y550-L01/hwY550-L01:4.4.4/HuaweiY550-L01/C00B246:user/ota-rel-keys,release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt Features : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt Features : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt Features : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: italiano
Locale: it_IT
InternalSD free space: 296951808
InternalSD path: /storage/sdcard1

**Comment by droidmjt** [comment] 2016-01-25 17:38
all right, i can see the error, i'll try to reproduce it and fix it, stay tuned. BTW, is the FTP server running in linux or windows box?

**Comment by Andr20** [comment] 2016-01-25 17:40
windows

**Comment by droidmjt** [comment] 2016-01-25 19:04
have you tried the latest version i just uploaded? when you create the network link, what path do you put in to the first box?

**Comment by droidmjt** [comment] 2016-01-25 19:06
this is my info:
1. /sdcard/dsroot/Network
2.ftp://username:password@your.ip.address:port/
3.myftp

try with that path on 1.

**Comment by droidmjt** [comment] 2016-01-25 19:09
ok i got the problem when its not saving the network link, its about the path in 1. 
i'll fix it

**Comment by droidmjt** [comment] 2016-01-25 19:24
when you click a file in your FTP and after it crashes, see from droidsound/fileCache/ftp... whether it downloaded your file at all. According to the log, it seems that it didn't even start to download your file since it crashes on nullpointer. Could you tell me which FTP server software you use?

**Comment by Andr20** [comment] 2016-01-25 19:29
Now i tried to select the path "dsroot" and the link is saved, but many times when I select the directory it doesn't go to the subdirectory, also trying to play the file I have to wait that is downloading then it starts, I am using serv-u for the ftp.

**Comment by droidmjt** [comment] 2016-01-25 19:30
all right, i'll get serv-u and see how it goes with that.

**Comment by droidmjt** [comment] 2016-01-25 19:46
yes i was able to reproduce your problem with servu, let's see ...

**Comment by droidmjt** [comment] 2016-01-25 20:09
fixed, stupid ftp lib problem

**Comment by droidmjt** [comment] 2016-01-25 20:22
https://www.dropbox.com/s/q9jqzte4jgkr4pr/droidsounde16647_36.apk?dl=0

**Comment by Andr20** [comment] 2016-01-25 20:33
OK, now it seems to work, the problem is the streaming, the plugin i am using is FFmpeg, to download the complete file from ftp it needs much time and i think the streming it it would be faster because it downloads the song little by little during the play

**Comment by droidmjt** [comment] 2016-01-25 20:34
what format you want to stream?

**Comment by Andr20** [comment] 2016-01-25 20:36
WMA

**Comment by droidmjt** [comment] 2016-01-26 05:17
in order to reproduce this, i need some example directory path from your FTP

**Comment by droidmjt** [comment] 2016-01-26 09:55
is this directory problem happening in FTP or locally or both?

**Comment by Andr20** [comment] 2016-01-26 10:01
i sent the ftp link via mail

**Comment by droidmjt** [comment] 2016-01-26 10:05
Just give me an example path that gives you problems so i can investigate it. For example that 003 - Trance Compilation path, is it just /sdcard/Music/003 - Trance Compilation or something else?

**Comment by Andr20** [comment] 2016-01-26 10:11
this problem doesn't happen only in some directory but it can happens with all the directory (on ftp), on sd memory i dont know, i don't save music there

**Comment by droidmjt** [comment] 2016-01-26 10:12
if i cannot reproduce the problem, how do you expect me to fix it?

**Comment by droidmjt** [comment] 2016-01-26 10:13
thats a common principle in software developing

**Comment by Andr20** [comment] 2016-01-26 10:16
sorry, when you go on ftp link, this problem it can happens in every directory you click, it can happens after some time

**Comment by Andr20** [comment] 2016-01-26 10:22
the path is /dsroot/server.lnk/006 - musica dance/003 - trance compilation, but how i said before it can happens everywhere on the ftp link

**Comment by droidmjt** [comment] 2016-01-26 11:56
all righty, i'll check it

**Comment by droidmjt** [comment] 2016-01-26 14:43
ok i was able to reproduce the problem, i'll get it fixed

**Comment by droidmjt** [comment] 2016-01-27 07:24
I have figured out the subdir problem, its about absolute and relative paths, for example filezilla ftp server including many unix based servers allows both when changing subdirectories while serv-u allows ONLY relative paths what is very annoying and makes things more complex. New build will be available at some point in this week, it will also have WMA streaming.

**Comment by Andr20** [comment] 2016-01-27 10:19
Ok I'll investigate on Serv-U, i tried to stream also MP3 and it says 
ERROR "stream plugin - Trying to connect remote" then "stream plugin - failed to connect remote" also if i disable the stream

**Comment by droidmjt** [comment] 2016-01-27 10:42
its because of the same reason most likely, i tried to check serv-u settings and couldnt find any switch for the relative/absolute path thing, there is a workaround for that luckily.

**Comment by droidmjt** [comment] 2016-01-28 07:48
solved the path problem completely now

**Comment by Andr20** [comment] 2016-01-28 15:55
WOW that's cool, I wait for the new version

**Comment by droidmjt** [comment] 2016-01-29 21:07
https://www.dropbox.com/s/k53q1zyxjanuh2z/droidsounde16647_38.apk?dl=0

try and see how it works

**Comment by Andr20** [comment] 2016-01-29 21:21
GOOD WORK! At the first impact seems to work, now i try for some hour and i let you know

**Comment by droidmjt** [comment] 2016-01-30 06:52
great :)

**Comment by Andr20** [comment] 2016-01-30 19:48
I tried it, after i listened some music from the same folder and i go to change folder it doesn't seem to update the list, the screen is empty, but this is not a serious problem, however now it work fine, GOOD JOB! :)

**Comment by droidmjt** [comment] 2016-01-30 19:54
yeah it doesn't update visited folders for a bit better performance, i can add a switch to change this behaviour

**Comment by droidmjt** [comment] 2016-01-30 22:30
https://www.dropbox.com/s/2bdx2sp7xuiqq9m/droidsounde16647_40.apk?dl=0
here, try this out, if the network caching switch works, then close this case, i think all is done here

**Comment by Andr20** [comment] 2016-01-31 10:51
Ok it seems to work now, that's fine, the support for this app is really good,1000000 of compliments, good to know that the support is really near to the user, Thank you very much. THIS APP IS THE BEST

**Comment by droidmjt** [comment] 2016-01-31 13:54
thanks :) I'll close this case, feel free to leave a comment

**Closed by droidmjt** 2016-01-31 13:54 UTC
