### ISSUE TITLE
Subtunes problems

### ISSUE THREAD

**Issue by Speedvicio** [droidmjt/Droidsound#350] opened 2017-03-21 15:56 UTC
Unable to play added subtunes on playlist section

**Comment by droidmjt** [comment] 2017-03-21 15:58
Closing this due to insufficient information. Once you provide more details, I'll reopen this.

**Comment by Speedvicio** [comment] 2017-03-21 16:19
It's always the same problem that i have reported on previous version (you have any email by me posted to you in the past).
I add subtune from nes, pce or amiga in "playlists > favorites" section, when i want to reproduce it, droidsound freeze for any seconds and skip all subtune until it found a non-subtune file added on playlist.
I can't explain the problem in a better way, english is not my language, but if you read my previous email, you can found the same problem and you in the past had solved it, but in latest release has reappeared.

**Comment by droidmjt** [comment] 2017-03-21 16:44
interesting, for SID music it works but not for nes for example, i'll check it

**Comment by droidmjt** [comment] 2017-03-22 13:38
https://www.dropbox.com/s/quxk1e8ive2zrj3/droidsounde167_25.apk?dl=1
Try this build. I tested it so that I added MegaMan2 subtunes to playlist and they seemed to play just fine.

**Comment by Speedvicio** [comment] 2017-03-22 22:04
I have tested this build.
On a droidsound clean install it work, but when you add another "non subtune music" the problem persists

**Comment by droidmjt** [comment] 2017-03-23 05:57
Can this be reproduced by using the Example songs? I have difficulties in reproducing your problem.

**Comment by droidmjt** [comment] 2017-03-23 06:26
nevermind, I was able to repro it now.

**Comment by droidmjt** [comment] 2017-03-23 07:25
https://www.dropbox.com/s/b88atwdokiqb049/droidsounde167_26.apk?dl=1
Try this, hopefully fixes your problem.

**Comment by Speedvicio** [comment] 2017-03-23 10:43
Thanks the last version work great, all solved.

**Comment by droidmjt** [comment] 2017-03-23 11:23
No need to do clean install, this was playqueue related.

**Comment by Speedvicio** [comment] 2017-03-23 13:07
Another bug, sane problem when I set "Play Song endlessly" on player

**Comment by droidmjt** [comment] 2017-03-23 13:12
you need to explain how to reproduce the problem and what exactly happens

**Comment by Speedvicio** [comment] 2017-03-23 13:43
I add 4 time , 2 vgm time and 2 messaggio subtunes on favorites playlist.
If i play It without set loop in player (Square icon behind random play), all' work.
If i set Play Song endlessly (infinite loop mode, buongiorno Square icon), all subtunes Will ignored

**Comment by droidmjt** [comment] 2017-03-23 14:09
Play song endlessly has no effect on subtunes, the only thing that affects subtunes playing from playlist is the setting in settings -> Playlists -> Single entry mode. It gets enabled by default, for example if you do clean install.

**Comment by droidmjt** [comment] 2017-03-23 14:15
I noticed another playlists related bug but its not related.

**Comment by Speedvicio** [comment] 2017-03-23 14:53
Sorry my english language continue to be terrible.
I try to explain better...
When i load a song from playlist and set "Play Song endlessly", the selected tune play in endless mode (how expected), then i try to load a new song from playlist... if this song is a unique file it will play correctly, but if it is a subtune "and Play Song endlessly" is enabled, the song will be skipped and will be load the first unique file available on playlist.

**Comment by droidmjt** [comment] 2017-03-24 18:24
https://www.dropbox.com/s/i2p76n52ocvykot/droidsounde167_27.apk?dl=1
This is the latest build, I'm not able to reproduce your problem no matter how I try it. I have Megaman2 subtune 2 and Sonic  the Hedgehog subtune 3 in playlist, even if I have endless loop enabled, they work perfectly.

**Comment by Speedvicio** [comment] 2017-03-25 12:39
Whit this release the problem remains.
But I do not stress yourself anymore.

**Comment by droidmjt** [comment] 2017-03-25 12:42
I can't fix something what I can't reproduce :( What you can do is try to bring me more detailed instuctions how to reproduce the problem. Did you have clean install? Did you change any settings? What are the exact files you used for this problem? More details the better.

**Comment by droidmjt** [comment] 2017-03-25 12:48
Also what you can try is, reset the Favorites so that it shows 0 entries, restart the application, add those subtune songs and see if the problem is still there.

**Comment by Speedvicio** [comment] 2017-03-25 12:55
To avoid conflicts, I delete all folder relative to droidsound on internal memory , after make a clean install of apk.
I add my two folder "music folder with any file in viarious compressed format" and module folder with inside any zipped and unzipped file ordered by composer or format file (this folder are in a external sd)
Then i add on playist 4 file, 
Two tunes on vgz file (plasma sword) 
And two file not zipped (Bad duddes  subtune 3 NES format,  and turrican 2 amiga world_2 subtunes 2).
If i select it from playlist > favourites without set "Play Song endlessly", I can always play it, but if i set "Play Song endlessly" and then select a subtune (bad duddes for example), it will do not play and droidsoud skip it and play the first non subtune file in this case vgz file plasma sword which is not a subtune.

**Comment by droidmjt** [comment] 2017-03-25 13:26
I was able to reproduce it now with the songs you mentioned, I'll fix it.

**Comment by droidmjt** [comment] 2017-03-25 19:47
https://www.dropbox.com/s/vjxwoxzmd3fak3y/droidsounde167_28.apk?dl=1
should fix your problem, as usual, do report any odd behaviour.

**Comment by Speedvicio** [comment] 2017-03-25 20:03
Working perferct.
You are my Hero!

**Comment by droidmjt** [comment] 2017-03-25 20:04
excellent, enjoy :)

**Closed by droidmjt** 2017-03-25 20:04 UTC
