### ISSUE TITLE
Options don't work on Nexus 5 

### ISSUE THREAD

**Issue by drew887** [droidmjt/Droidsound#145] opened 2015-01-05 02:32 UTC
They render as static for a few moments or until you press on a checkbox. Also when connecting to remotes it will report an error even though it successfully connects and plays.

![droiderr](https://cloud.githubusercontent.com/assets/2347730/5608659/d9713c1e-9458-11e4-8bc3-d99a9331ef9f.png)

**Comment by droidmjt** [comment] 2015-01-05 05:39
I uploaded 7 hours ago another binary, have you tried that? I just tested it with Nexus 5 (4.4.4) and Netradio worked ok + Settings. I also tested it with Genymotion Nexus 5 (5.0.0) and all worked ok. Later I can test it with Nexus 10 (5.0.0) if it works.

**Comment by drew887** [comment] 2015-01-05 23:40
With the new image it does this at first run, but the remotes error is gone :D. Also I'm running 5.0.1

![droiderragain](https://cloud.githubusercontent.com/assets/2347730/5621974/fbe5d8f2-9509-11e4-9b24-3ab1e011d9d6.png)

**Comment by droidmjt** [comment] 2015-01-06 08:15
I have no device that would have 5.0.1 :( Also i cannot reproduce the problem with current devices.

**Comment by drew887** [comment] 2015-01-07 01:55
Here's a video of it happening in action, it'll do it almost every time I go into the settings menu.
https://www.youtube.com/watch?v=mpR5DV_xWfk

**Comment by droidmjt** [comment] 2015-01-07 05:09
bigger problem is that i have no 5.0.1 device here, it seems to be 5.0.1-only problem :(

**Comment by droidmjt** [comment] 2015-01-07 06:40
Correction, I managed to test with 5.0.1 device, Nexus 10, unfortunately i couldn't reproduce the problem with it.

**Comment by droidmjt** [comment] 2015-01-09 13:18
i'll close this since there's nothing that can be done for this, at least for now

**Comment by droidmjt** [comment] 2015-01-30 05:45
Finally I was able to reproduce this problem, not with my own device tho. It seems to happen only with Nexus 5 OS version 5.00 and 5.01. I tried it also with Nexus 10 OS version 5.02 and no problems. I have no idea what causes that problem. It hasn't been reported before.

**Comment by droidmjt** [comment] 2015-03-10 11:18
good news, update your phone to 5.1 and the problem should disappear

**Closed** 2015-03-15 07:16 UTC
