### ISSUE TITLE
Crash on scanning certain files in newest version

### ISSUE THREAD

**Issue by Zeether** [droidmjt/Droidsound#420] opened 2018-06-16 03:48 UTC
This has been happening with one zip file that had Japanese characters and a .gz file. I don't have a crash log because it won't generate one.

**Comment by droidmjt** [comment] 2018-06-16 03:55
please send me the zip file so I can fix the problem

**Comment by droidmjt** [comment] 2018-06-16 04:07
or is it enough if I just create a zip file using japanese characters and place a .gz file inside?

**Comment by droidmjt** [comment] 2018-06-16 04:20
I created a zip file using japanese characters, no problems there, can enter the archive with filesystem browser normally and db browser option works also. Then I renamed one .vgz file using japanese characters, same deal. I need more details how to reproduce the crash. You can get crash infos by using adb logcat.

**Comment by Zeether** [comment] 2018-06-16 05:15
I deleted the two files since they were zipped folders anyway and it scanned fine.

**Comment by droidmjt** [comment] 2018-06-16 08:17
I'll close this issue since there is nothing I can do at the moment. If you provide a zip file what fails in the app or instructions how to create one I'll reopen this issue again.

**Comment by jimbo1qaz** [comment] 2018-07-02 05:32
This encrypted 7z archive crashes when scanning DB:
https://www.dropbox.com/s/010prwohlxf8vpl/password%3Dwat.7z?dl=1

password is `wat`. File names (not just contents) are encrypted.

**Comment by jimbo1qaz** [comment] 2018-09-19 11:01
Issue is still not fixed. I cannot use DB browsers since they crash.

After updating to 121, all my bookmarks are gone since apparently non-DB folder browsers don't support bookmarks. Is this a newly introduced change?

**Comment by droidmjt** [comment] 2018-09-19 11:10
for some reason the jul 2 msg was completely forgotten, i'll check this again

**Comment by droidmjt** [comment] 2018-09-19 13:50
tested the files you sent, copied psfs to /sdcard/Music/ and used DB browser, all worked, zipped the psf files and copied the zip to same folder, created DB browser, worked, using build 122

**Comment by droidmjt** [comment] 2018-09-19 14:11
I hope you are not trying to process passworded archives

**Comment by droidmjt** [comment] 2018-09-19 14:18
tested also with build 121, no problems

**Closed by droidmjt** 2018-09-19 14:18 UTC

**Comment by jimbo1qaz** [comment] 2018-09-20 00:32
I kept several bad-sounding SFX PSF files from the game rip in a password-protected ZIP. This prevents foobar2000 from scanning or playing them when I'm shuffling songs.

If you don't want to fix DSE crashing when it encounters password PSF files, I'll just delete the ZIP files on my phone.
