### ISSUE TITLE
Crash on PSF in 7z scan (Kindle HDX)

### ISSUE THREAD

**Issue by hcs64** [droidmjt/Droidsound#166] opened 2015-05-07 16:35 UTC
I'm experiencing a crash while scanning the Final Fantasy VIII set available at psf.joshw.info, on both 1.662 and the current debug version, it seems to get partway through scanning the file and then Droidsound-E crashes. That 7z archive has both PSF and MP3 files. I am running on a Kindle HDX, it does not crash on the same file on a pretty weak phone (Samsung Exhibit 2) or a decent tablet (Samsung Galaxy Tab S). There is also no problem if I extract the files and just play them directly from a directory.

I'd try to debug this myself but I don't see the current version of the source, am I overlooking something?

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException
	at com.droidmjt.droidsounde.plugins.HEPlugin.loadInfo(HEPlugin.java:342)
	at com.droidmjt.droidsounde.FileIdentifier.tryLoad(FileIdentifier.java:229)
	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:308)
	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:492)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:880)
	at com.droidmjt.droidsounde.database.SongDatabase.doScanDir(SongDatabase.java:1072)
	at com.droidmjt.droidsounde.database.SongDatabase.access$400(SongDatabase.java:92)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:253)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:151)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:283)
	at java.lang.Thread.run(Thread.java:856)
============================
Droidsound-E version: 34
Droidsound-E Build: 3
Time: Thu May 07 12:05:28 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: Amazon/thor/thor:4.2.2/JDQ39/13.3.2.4_user_324002120:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 6143033344
InternalSD path: /storage/emulated/0

**Comment by hcs64** [comment] 2015-05-07 16:44
I tried rearchiving the set as a .zip, that file scanned successfully.
I then tried rearchiving it as a .7z, that crashed while scanning as before.

**Comment by droidmjt** [comment] 2015-05-07 17:53
before anything, do you have ".nomedia" file inside /droidsound/ folder, if not, create it and try again

**Comment by droidmjt** [comment] 2015-05-07 18:09
the latest beta I have uploaded today creates that file automatically

**Comment by droidmjt** [comment] 2015-05-07 18:16
the current source code in the github is very old, it's no use :(

**Comment by droidmjt** [comment] 2015-05-07 18:31
good thing im able to reproduce this problem, i'll investigate it

**Comment by droidmjt** [comment] 2015-05-07 18:33
oh hell, it's filecache size problem, increase the cache size to 64MB and it should work :(

**Comment by hcs64** [comment] 2015-05-07 19:39
Ok, increasing the filecache to 64 MB works, thanks for the workaround. Any reason for why this should be specific to my Kindle (my other two Android devices were also set to 32 MB)?

**Comment by hcs64** [comment] 2015-05-07 19:54
Hmm, more trouble: if I have another .7z to scan also (I tried with Final Fantasy Tactics), then it still crashes during scanning (it does FFT, then FF8, then crash). Bumping the filecache up to 128 MB seems to assuage that... this is on 1.662. Is it going to need to be big enough to fit two files?

**Comment by droidmjt** [comment] 2015-05-07 20:15
i'll check the FFT, I added new code so that this doesn't happen again (hopefully). I need to see the FFT 7z first.

**Comment by droidmjt** [comment] 2015-05-07 21:18
there is new beta in dropbox link, try it out, it should work even with 32MB cache

**Comment by Level99OCR** [comment] 2015-05-08 12:24
Was this another one of those things that's tied to a non-stock kernel, mjt? I know filecache, besides special characters, has been THE worst component of Droidsound to debug and fix.  It's just so dependent on the OS behaving nicely with the quick decompress/scan/remove.

I've also grabbed the latest and will be trying it with some known filecache offenders.

**Comment by droidmjt** [comment] 2015-05-08 12:51
This bug was just related to the filecache size being almost the same with the .mp3 filesize, due to my stupid logic it wiped the filecache completely and tried to read the file afterwards thus causing filenotfound exception.

**Comment by hcs64** [comment] 2015-05-08 14:00
Looks good, no crashes on my test cases.

**Comment by droidmjt** [comment] 2015-05-09 06:47
i'll close this, feel free to reopen this if the problem comes back

**Closed by droidmjt** 2015-05-09 06:47 UTC
