### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#170] opened 2015-05-21 15:41 UTC
I was wondering if you had any plans to implement an option to disable reverb on the PSF plugin. 

Foobar has this option which is why I ask.

Also I'm not sure if you know or not but the USF plugin now has an option to set a custom sample rate for it. Setting a game like GoldenEye to 44k makes a difference.

Also one last question, do think maybe in the future we could have an option to disable certain plugins that we don't use to free up RAM?

 I ask this because my brother's android 4.1 now crashes when scanning folders to add a playlist.

**Comment by droidmjt** [comment] 2015-05-21 17:34
That USF library will be added once its fully finished.

The plugin enable/disable I added to my todo list already, good idea :) It will be in v1.664 version or earlier beta. Also the PSF reverb fix will go to v1.664. Once I have added these features I will release beta version for you to test.

**Comment by 47iscool** [comment] 2015-05-21 17:35
Hey thanks a lot, will test asap.

**Comment by 47iscool** [comment] 2015-05-21 17:35
Okay sorry, read it a little too fast.

**Comment by droidmjt** [comment] 2015-05-21 17:36
hehe, np, v1.663 will be released within next 24 hours

**Comment by 47iscool** [comment] 2015-05-21 17:39
Alrighty then.

I can only use WiFi on certain days on my phone, so I should be able to get it Sunday.

**Comment by droidmjt** [comment] 2015-05-22 03:43
close this case, i'll reopen it once those new features are in beta version

**Comment by 47iscool** [comment] 2015-05-22 21:54
Alright. Got it sooner than I thought

**Comment by droidmjt** [comment] 2015-05-23 09:30
Added PSF reverb setting, check out the unofficial v1.664 from link below.
https://www.dropbox.com/s/m1zqo3ix33fxevh/droidsounde1664.apk?dl=0

**Comment by 47iscool** [comment] 2015-05-23 18:17
Got it.

**Comment by 47iscool** [comment] 2015-05-23 18:41
Works great, thanks again.

**Comment by droidmjt** [comment] 2015-05-24 09:24
excellent, i'll close this and reopen once the other feature has been added

**Comment by 47iscool** [comment] 2015-05-24 14:39
Okay.

**Comment by droidmjt** [comment] 2015-06-05 14:00
https://www.dropbox.com/s/k2h1j2mxh7m8p2b/droidsounde1664_06.apk?dl=0

**Comment by droidmjt** [comment] 2015-06-06 07:24
about the crash caused by scanning a playlist, I would like to see the crashlog

**Comment by 47iscool** [comment] 2015-06-06 23:08
Unfortunately my brother deleted the droidsound folder he had. We did however find out that it was caused by scanning vgm files. They weren't gzipped either. Anyway, I'll make sure to get the latest one from the link.

**Comment by 47iscool** [comment] 2015-06-07 14:31
Resampling works great, thanks.

**Comment by droidmjt** [comment] 2015-06-07 14:37
excellent :)

**Comment by droidmjt** [comment] 2015-07-27 16:33
>>Also one last question, do think maybe in the future we could have an option to disable certain plugins that we don't use to free up RAM?

this feature is done, i'll add another feature and upload new binary for you to test

**Comment by droidmjt** [comment] 2015-07-27 17:34
https://www.dropbox.com/s/8h53xv1mi60ax3r/droidsounde1664_33.apk?dl=0

**Comment by 47iscool** [comment] 2015-07-29 00:03
Thanks!

**Closed** 2015-07-29 04:00 UTC
