### ISSUE TITLE
mp3s don't loop

### ISSUE THREAD

**Issue by GL1TCH04** [droidmjt/Droidsound#214] opened 2015-11-26 16:28 UTC
still an android 5.0.2 based custom rom

using the test build that had fixed BASS libraries

it's strange because this used to work just fine, but suddenly it doesn't anymore

**Comment by droidmjt** [comment] 2015-11-26 16:33
yeah i think its broken, the current state of the DSE is a mess, i had to improve something

**Comment by GL1TCH04** [comment] 2015-11-26 16:40
well the test build used to work, it just kinda suddenly quit doing that

**Comment by droidmjt** [comment] 2015-11-26 17:01
what test build? be more specific please. The recent one? what build number?

**Comment by GL1TCH04** [comment] 2015-11-26 21:09
the build that you linked me in my last issue where playing mp3s would cause my phone to lock up 
build is 1.6647
files are local on sdcard

**Comment by droidmjt** [comment] 2015-11-27 07:11
is it so that the BASS version started working eventually?

**Comment by GL1TCH04** [comment] 2015-11-27 12:22
yeah basically
the one in that specific test build actually worked 100% fine with looping and playback, but after a few days, it just automatically started to have looping issues

**Comment by droidmjt** [comment] 2015-11-27 12:25
i need to know exact plugin name, was it BASS or FFmpeg that you are talking about?

**Comment by droidmjt** [comment] 2015-11-29 04:56
https://www.dropbox.com/s/36tdnx1oajzejf3/droidsounde16647_06.apk?dl=0

**Comment by droidmjt** [comment] 2015-11-30 20:56
I'll close this case, reopen this case if the problem is still there.
https://www.dropbox.com/s/f57pcp2j7m61jfy/droidsounde16647_07.apk?dl=0
above is the latest build

**Closed by droidmjt** 2015-11-30 20:56 UTC

**Comment by GL1TCH04** [comment] 2015-12-07 19:58
sorry for the very late reply, just tried out the test build, looping works just fine now
can't guarantee, that it's because of the build though, as i've stopped using the S6 port

**Comment by droidmjt** [comment] 2015-12-07 20:42
the S6 port is the seed of evil here :) I recommend to use official builds or ROMs like Cyanogenmod that are well-known.

**Comment by GL1TCH04** [comment] 2015-12-07 21:06
i would use cyanogenmod, but i've honestly come to dislike it, for reasons like terrible battery life
besides, i have a galaxy s4 with lots of features that are not available in cyanogenmod
i'll just stick with a rom that bases on the S4/5 software instead, these work better anyways

**Comment by droidmjt** [comment] 2015-12-07 21:32
good idea :) I agree, the battery life in cyanogenmod is terrible. I use it for testing purpose tho, so it's not a big problem for me.
