### ISSUE TITLE
mounting USB storage while droidsound running messes it up

### ISSUE THREAD

**Issue by filevans** [droidmjt/Droidsound#238] opened 2015-12-27 15:21 UTC
if you mount USB storage while droidsound running it messes everything up, and when you go back into droidsound there are no files displayed, and pressing back to root folders/ shortcuts still doesnt display anything, even forcing close and clearing cache and restarting the folders have still vanished

the only way to resolve it then is doing reset settings

**Comment by droidmjt** [comment] 2015-12-27 15:23
thats bad, i don't know how to fix it

**Comment by filevans** [comment] 2015-12-28 00:57
You know if you plug your phone by usb into your PC and Mount the sdcard , that's when it happens, it goes wrong because it loses ability to read/ write to phone storage. That's what happens

**Comment by droidmjt** [comment] 2015-12-28 06:59
cancel my earlier rant, what should do you suggest that should be done when USB is connected?

**Comment by filevans** [comment] 2015-12-30 15:23
well to get round the problem at the moment, when i want to copy files through usb from pc to phone, i have to close droidsound, because if i dont i get the problem i mentioned, and it has to be completely reset to display any folders / files whatsoever

so if there was a way droidsound could recognise that it no longer has access to the device's memory / sd card, and somehow unmount itself, but i dont know if that is too complicated to do

**Comment by droidmjt** [comment] 2015-12-30 15:31
the only thing i can do here is that, if the sdcard is not in RW mode, i prevent it writing, it should be able to read songs normally anyway

**Comment by filevans** [comment] 2015-12-30 15:33
yes it stops reading altogether, and no folders display, i could take a pic of it happening but then i will have to reset my settings, and prefer not to, but just imaging being in dsroot, and absolutely nothing displays, no network, no database, no folders, just completely blank, and restarting the program, even after disconnecting usb, doesnt bring them back, you have to do a full settings reset

**Comment by droidmjt** [comment] 2015-12-30 15:40
must be related to OS version, i cannot reproduce the same with 5.1.1, i try with earlier versions. What version you have btw ?

**Comment by filevans** [comment] 2015-12-30 15:45
Android 4.4.2

i havent had this probem on any other programs, but they probably read the directory in a different way

ive just had a message on things like whatsapp to say sdcard not accesible, but doesnt mess anything up

**Comment by filevans** [comment] 2015-12-30 23:32
![screenshot_2015-12-30-19-28-35](https://cloud.githubusercontent.com/assets/14978933/12059135/b299e20a-af2b-11e5-8c26-8cf7b3f98b7c.png)

worse now
as now the program completely crashes, and when you load it back up while mounted on usb, it crashes again. then when you disconnect usb mount and load it back up you get the same problem, all your directories have gone, as you can see in the screenshot

if droidsound crashed and protected your folders, that would be a reasonable option
but instead if crashes and you lose all your folders

so now ive got to reset all the settings and gui again

**Comment by filevans** [comment] 2015-12-30 23:42
i noticed you put a new option to have normal click to sort as default, but it is better as a long click, so could this be made at least made defuault unticked, and if people want tap then they can tick it, or if ticked then change option to be "make long click" as default

**Comment by droidmjt** [comment] 2015-12-31 09:49
I have a feeling that the USB mounting is related to the SQL access, since it requires RW access to it by default, i can make it so that if USB is mounted, use it as Read-Only mode. I'll test it also with 4.2.2 and see if I can reproduce the problem.

**Comment by filevans** [comment] 2015-12-31 13:11
4.4.2 i have not 4.2.2...

**Comment by droidmjt** [comment] 2015-12-31 14:13
i don't have 4.4.2 physical device. If I can get it fixed for 4.2.2, then it works also with 4.4.2

**Comment by filevans** [comment] 2015-12-31 14:22
just was clarifying just in case, thanks

**Comment by filevans** [comment] 2015-12-31 20:07
please could you set default options for the long press to change sorting, and parent folder as author, as i am testing a lot of versions and i have to keep resetting my settings, and these settings are better on
anyone who wants to change the settings can do it easily

**Comment by droidmjt** [comment] 2016-01-01 06:33
tested now with 4.2.2, 4.4.4, 5.1.1, started DS-E, started playing music, connected USB port to USB stick and/or computer, filecopying works fine while DS-E is running.  I do remember that I once encountered similar event when mouting USB while using DS-E. Unfortunately it happened only once and many months ago. I wish I could reproduce this problem again.

**Comment by droidmjt** [comment] 2016-01-01 06:34
What kind of device do you have, brand and model?

**Comment by droidmjt** [comment] 2016-01-01 07:03
all my devices are samsung and I'm using correct Samsung drivers for Windows, maybe that's why it works. But that doesn't explain why the USB stick with OTG-cable works.

**Comment by filevans** [comment] 2016-01-01 13:36
not sure if its relevant but im not using an sd-card, just phone memory, i dont have an sd-card in there at all, could you test that scenario? remove sdcard and install droidsound on main memory and see if that changes anything for you

**Comment by droidmjt** [comment] 2016-01-01 13:45
I have the app in internal SD memory all the time, i can try so that i remove the external SD card

**Comment by filevans** [comment] 2016-01-01 13:53
yes because having somewhere else for the system to read/write to might affect the scenario

**Comment by droidmjt** [comment] 2016-01-01 15:06
ok this is what I did: removed external SD card, started the app, started a song, mounted USB stick, performed full rescan, started another song from USB stick. All fine. Used Android 4.4.4 version. 4.2.2 never had external SD card and 5.1.1 device has no external SD card slot.

**Comment by filevans** [comment] 2016-01-01 15:33
best to add a couple of filesystem browsers, and have it browsing one of them during mounting

**Comment by droidmjt** [comment] 2016-01-01 15:43
same deal, i've used filesystem browser, the only additional thing that happens in the middle is that after mounting it automatically opens up Android OS own file browser, i'll close it and go back to the app, all works fine.I have done so many variations with this thing so if it would be easy to reproduce, it would have triggered already, and for the record, nobody ever reported this except you :)

**Comment by filevans** [comment] 2016-01-01 15:52
ok forget it then i suppose, maybe i need to do a full reset and clear cache

**Comment by filevans** [comment] 2016-01-01 15:53
i wonder if its because i have things like super su installed, and ive installed a program to give me full root write access

**Comment by droidmjt** [comment] 2016-01-01 15:55
actually, that 4.4.4 device i have is also rooted but is using stock OS, i used this clockworkmod thingy.

**Comment by droidmjt** [comment] 2016-01-01 15:57
ignore that, it seems i lost the root access, just tried with ES File Explorer.. oh well

**Comment by droidmjt** [comment] 2016-01-01 15:57
we can reopen this when we know how to reproduce this correctly, I dislike cases like this :(

**Comment by droidmjt** [comment] 2016-01-01 16:02
close this case, nothing we can do here

**Closed** 2016-01-01 16:04 UTC
