### ISSUE TITLE
VGMStream slow to load with some formats

### ISSUE THREAD

**Issue by Galindorf** [droidmjt/Droidsound#380] opened 2017-07-04 03:15 UTC
I'm playing the Eternal Darkness files, in ADP format and they take a while to load (3-10 seconds). 
I'm noticing the same with GENH files from Ico.
..and also the ADX files from Okami (17+seconds to load, between each song!) (and then I got the Droidsound-E has stopped working box)

Is the VGMStream plugin just kinda... persnickety?

**Comment by droidmjt** [comment] 2017-07-04 04:50
Send me the files what causes this problem.

**Comment by droidmjt** [comment] 2017-07-04 05:12
Nevermind, tested those files you mentioned, they all work, I have updated the VGMStream library recently, I'm not sure if it's because of it but I cannot reproduce your problems. Wait for a new binary.

**Comment by Galindorf** [comment] 2017-07-04 05:30
Thanks, mate~

**Comment by droidmjt** [comment] 2017-07-05 05:12
https://www.dropbox.com/s/aappymhlk9cwotb/droidsounde167_52.apk?dl=1
try this

**Comment by droidmjt** [comment] 2017-07-08 11:24
I'll close this case, leave a msg.

**Comment by droidmjt** [comment] 2017-07-08 11:24
https://www.dropbox.com/s/whjjsx93kaey85w/droidsounde167_53.apk?dl=1

**Comment by Galindorf** [comment] 2017-07-09 19:28
I updated to the 167_52 version and it was still behaving with the slow loading. I was going to try the new link but it now shows as 'not found.'

**Comment by droidmjt** [comment] 2017-07-09 19:30
get the latest from the front page, build 167_55

**Comment by droidmjt** [comment] 2017-07-09 19:30
https://www.dropbox.com/s/3nvg61w8ysxk0om/droidsounde167_55.apk?dl=1

**Comment by droidmjt** [comment] 2017-07-09 19:33
are you loading these files from archives?

**Comment by Galindorf** [comment] 2017-07-09 19:45
They are indeed from archives. I am on 167_55 now. If anything it's even slower than before. The song length seems to make no difference. It actually slows my whole phone down (as in if I hit the volume button it hangs until the song starts to play, and then the volume is changed).

**Comment by droidmjt** [comment] 2017-07-09 19:54
What kind of archive, 7z?

**Comment by Galindorf** [comment] 2017-07-09 19:56
Yes, 7z. Okami seems to be the worst offender, but it is an *enormous* zip file. Is it maybe trying to read the entire zip file every time it loads a new song?

**Comment by droidmjt** [comment] 2017-07-09 19:58
7z are known to be slow due to solid-block archiving method. Extracting those are real pain, you need to repack them to normal ZIPs or 7zips without solid-block method. How big is the okami zip?

**Comment by droidmjt** [comment] 2017-07-09 20:03
nevermind, checked it, 588MB, i'll zip it and see how it works

**Comment by droidmjt** [comment] 2017-07-09 20:05
normal zip files shouldn't cause any kind of troubles, it will find the entry from the table at the end of the archive and extract the desired file

**Comment by Galindorf** [comment] 2017-07-09 20:09
ok. I'll extract my .7z's and make them into ZIP. Thank you so much!

**Comment by droidmjt** [comment] 2017-07-09 20:10
just incase, repack that okami also, i just used 7zip to repack those files to zip (deflate + normal compression), works very fast

**Comment by Galindorf** [comment] 2017-07-09 20:31
Repacking the .7z files into .zip files completely did the trick. *happy dance* Rock on, man!

**Comment by droidmjt** [comment] 2017-07-09 20:33
excellent, close this case since it's solved :)

**Closed** 2017-07-09 20:40 UTC
