### ISSUE TITLE
[Potential Enhancement for Usage] - Changes to filescan

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#218] opened 2015-12-07 21:30 UTC
Two quick insights that might prove beneficial in the long run to usability in-general.

1) As of the last time I checked, the player stops playing if it detects a scan going on when the current song ends. This is to prevent force closes from the app for when a scan is going and the song changes, because the player tries to grab info from the database but the database is open by the scanner and can't be read. A workaround to this would be to copy the current database to a secondary file with a different name, then use that secondary file for the scan so the player can keep using the current database to play music. Then, whenever the scan is done and it detects a change in player activity, the old database can be deleted and the new one renamed to replace the old. To make this fully functional, the scan itself would have to have a different UI element, possibly a "Hide in Background" button that removes it from overlaying the rest of the app or possibly putting a scan status in the notification area.

2) As of late, it seems like the filescan has the potential to leave behind a lot of zero-byte files. I know previously it was set to remove files when scanning of a specific file was done, not sure when that behavior changed or if its just a bug on my end but maybe look into how filescan is leaving files in the filecache? I'll see if I can reproduce this reliably but I'll be honest, I've been using it more and testing it less because it's gotten so stable and usable as of late. I find myself actually using the app instead of trying to find ways to break it :)

**Comment by droidmjt** [comment] 2015-12-07 21:37
about the 2), I can make it so that after the scan the filecache gets wiped, would that be ok? Crap, was it like that before?!?!?

**Comment by droidmjt** [comment] 2015-12-07 22:22
https://www.dropbox.com/s/mxc3mjh6yq7gdlr/droidsounde16647_08.apk?dl=0
request 2) is there, do test if it works

**Comment by droidmjt** [comment] 2015-12-08 06:53
crap, just realized that when a song is playing and after a scan ends it performs the filecache wipe, it also wipes the file that is currently being played -> crash, i need to test if this is really possible or would it skip the file currently in use.

**Comment by droidmjt** [comment] 2015-12-08 06:54
about the 1), this shouldn't be a problem anymore since i have renewed the queueing thing, i'll do some tests

**Comment by droidmjt** [comment] 2015-12-08 18:34
https://www.dropbox.com/s/p4633mhy6uml428/droidsounde16647_09.apk?dl=0
this should work better, it wipes all the files after scanning but leaves the file in use there.

**Comment by Level99OCR** [comment] 2015-12-08 22:41
Thanks for the quick attention! Testing tonight and tomorrow.

**Comment by Level99OCR** [comment] 2015-12-09 12:16
I'm assuming that 1 hasn't been enabled yet, since player halted after song ended but still showed as playing (gives pause option on overlay controls) when another scan was going. Verified that if a song is playing while a scan completes, the playing file is left in filecache and the rest is wiped. No crashes during scan or after completion yet, things are much more responsive between adding file browsers now that the filecache is super clean. Player will still stop and not continue to next song if a scan is going on at the time, and once scan completes user needs to manually play things or skip to next track to listen to music again. 
That does bring up one other part I believe should be highlighted. If a song ends during scan, is it possible for droidsound to fetch the next file in the queue, put it in the filecache and play it while a scan is ongoing as well? If the answer is no, an automated resume of music after scan would be preferred.

**Comment by droidmjt** [comment] 2015-12-09 17:35
>> If a song ends during scan, is it possible for droidsound to fetch the next file in the queue, put it in the filecache and play it while a scan is ongoing as well

This is done.

**Comment by Level99OCR** [comment] 2015-12-11 15:16
No worries. I know you got a lot on your plate. I have one other tiny enhancement I'm going to open but, again, you focus on whatever is your priority. Thanks!

**Comment by droidmjt** [comment] 2015-12-11 15:34
it might be possible but requires some new stuff here and there, personally, what i do is , while im playing something i never add anything new, once i'm done adding new stuff, then i play, and scanning + playing at the same time is not even possible on certain devices since scanning also  consumes CPU

**Comment by Level99OCR** [comment] 2015-12-11 15:48
True, true. My stuff is organized in such a way that it's easy to transport and update, so my scans normally take a lot longer in-general. I'm use to carrying around two devices (one to test and one to actually use) so it's not a huge impact to me either way, but I can see some residual benefit in the long run to this.

**Comment by droidmjt** [comment] 2015-12-11 18:00
bad news, after many attempts to get 1) done, it's no go, it requires lots of changes and due to current architecture, it would take very long time to get fixed. It's not about the DB being in use, its about threading/synchronization, at least 2) works and after the scanning, the playing resumes automatically.

**Comment by droidmjt** [comment] 2015-12-12 07:07
I'll try one more time, i got an idea...

**Comment by droidmjt** [comment] 2015-12-12 08:47
ignore my earlier post, 1) and 2) works now as expected.

**Comment by filevans** [comment] 2015-12-16 15:39
shall we close this issue now then?

**Comment by droidmjt** [comment] 2015-12-16 15:50
lets be gentlemen here and handle own tickets :)

**Comment by filevans** [comment] 2015-12-16 15:53
no i was just trying to help you organise whats done, to make it easier

**Comment by droidmjt** [comment] 2015-12-16 15:59
well, i guess its ok :) personally i don't like too many open tickets, must be open-tickets-phobia

**Comment by Level99OCR** [comment] 2015-12-17 14:43
Agreed about closing tickets as is feasible, normally MJT ups a new build for testing, then I test it, if it works I close it, kick back a beer to celebrate :)

**Comment by droidmjt** [comment] 2015-12-25 09:58
reopen this case if the problem is still there or leave a comment

**Closed by droidmjt** 2015-12-25 09:58 UTC

**Comment by Level99OCR** [comment] 2016-01-02 16:43
This is working fine enough, appreciate the work on this.
