### ISSUE TITLE
m4a playback cuts out first second of the song

### ISSUE THREAD

**Issue by theGIZOID** [droidmjt/Droidsound#486] opened 2019-06-04 23:32 UTC
Device: Sony Xperia Z2
Android Version: 9 (Pie)
DS-E Build: 1.67.164

As the title already states: upon playback about one second of any m4a file is being skipped but the rest is being played like intended.

**Comment by droidmjt** [comment] 2019-06-05 04:40
I tried with 5 different m4a songs, couldn't reproduce the problem. Could you email me one m4a song so I can reproduce the problem? Also tell me what switches you have enabled, for example fadeout, songlength stuff etc etc

**Comment by theGIZOID** [comment] 2019-06-05 09:24
Sent you an email but I also have an suspicion that this MIGHT be a ROM related issue somehow. I have tried the same m4a files in Play Music and the default Music player and I get the same skipping issue.
I also have no issues when playing m4a files back on windows in any player that I have available.

**Comment by droidmjt** [comment] 2019-06-05 09:28
tested the song, no problems, later today I can try with custom ROM

**Comment by droidmjt** [comment] 2019-06-05 09:29
do you have this song inside an archive or as a separate file?

**Comment by theGIZOID** [comment] 2019-06-05 09:44
separate file

**Comment by droidmjt** [comment] 2019-06-05 14:58
I tested with RR ROM (Android 7.1.2) and worked fine. Too bad I don't have a phone where I could use Android 9 custom ROM.

**Comment by theGIZOID** [comment] 2019-06-05 15:16
I could test Android 9 on another device, a Samsung Galaxy S5 on which I could install Android 9 via LoS 16.0. But right now I don't have that phone at hand.

**Comment by droidmjt** [comment] 2019-06-05 15:59
does logcat show any special activity when you try to play m4a files?

**Comment by droidmjt** [comment] 2019-06-06 04:38
I'll close this, I don't think there is anything I could fix here.

**Closed by droidmjt** 2019-06-06 04:38 UTC

**Comment by froggestspirit** [comment] 2019-06-21 01:36
Are you playing over a bluetooth speaker? My car stereo used to mute when it was between songs, cutting into a second or two of songs starting
