### ISSUE TITLE
[Internal Function Change Request] Cleanup of Directories DS uses in root of Internal Storage

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#279] opened 2016-04-22 16:59 UTC
Two hopefully very simple changes to how Droidsound E works. Extremely low priority but good for storage access/logic.

Currently, Droidsound E creates three directories on the root of the Internal Storage on first load: /Droidsound/, /dsroot/, and /DSEMusic/.

/dsroot/ is left over from when SwimsuitBoys started the app, I believe. The Networks, Examples, and pointers to added Filebrowsers go in there. Can this be made a subfolder of /Droidsound/, to tidy up how Droidsound looks in root storage?

Similarly, can you enable a prompt to ask whether or not to create /DSEMusic/? It's empty by default, and while its good for some people to have a place they can drop music and have it be scanned and loaded, its just another folder I end up deleting to clean up the directory listing on the root of internal storage.

No actual bugs, just minor inconveniences and stuff which could be a little cleaner for the app.

**Comment by droidmjt** [comment] 2016-04-22 18:28
Let's see if I can get this done in a comfortable way.

**Comment by droidmjt** [comment] 2016-05-15 04:51
bugger, why i didn't do this from the beginning, now its real pain in the neck :(

**Comment by Level99OCR** [comment] 2016-06-01 13:55
Oy, I can only assume that the directory hooks are multiple and now deeply embedded in the code. That sucks. It's not the end of the world if this is tabled or indefinitely postponed, especially if you have other higher priorities in mind. Speaking of, any idea of what's left to do before putting this back on the play store for availability?

**Comment by droidmjt** [comment] 2016-06-01 15:12
Maybe it's not problematic after all, we'll see :) I will start cracking this after my present problems. 
Ah playstore, most likely it will never return to playstore, maybe at beta stage, but no promises.

**Comment by droidmjt** [comment] 2016-06-02 02:51
all right, here's the thing, it's no big deal to change the code to make it use /droidsound/dsroot BUT the 'pain in the neck' part is how to get existing users to use the new path smoothly. Full rescan won't help in this case since their files are in old dsroot. I think the only way to solve this is to write some function to check version number then do some file copying. I dislike this kind of hacks :(

**Comment by droidmjt** [comment] 2016-06-07 14:25
this is done, i test it myself before uploading a new binary, wasn't that bad after all, should have tried coding it before ranting :)

**Comment by droidmjt** [comment] 2016-06-07 15:21
https://www.dropbox.com/s/7lqqmjoor0o9zcr/droidsounde16647_68.apk?dl=0
please test it, don't remove the existing install before installing this one. Incase of a crash, collect crashlog.

**Comment by droidmjt** [comment] 2016-06-07 23:06
i'll close this, leave a comment

**Comment by Level99OCR** [comment] 2016-06-08 13:15
I'll grab it this afternoon and give it a go, thank you very much for your diligence.

**Comment by droidmjt** [comment] 2016-06-08 13:18
great, no problem.

**Comment by Level99OCR** [comment] 2016-06-08 17:15
I installed this overtop my install of 66, and while it didn't crash, it removed all of my filestore locations. It also showed up as if it was a fresh install with the popup window telling me as such.

**Comment by droidmjt** [comment] 2016-06-09 00:11
your old dsroot should have those old filestore locations, it only copies files. Did it create droidsound/dsoot folder? did the the dsroot files get copied there?

**Comment by droidmjt** [comment] 2016-06-09 00:38
ok i was able to reproduce it, no worries, if you manually copy the old dsroot contents to new dsroot all is fine again

**Comment by droidmjt** [comment] 2016-06-09 00:38
what i dont understand is that how come it didnt copy all the files, i will investigate and test more

**Comment by droidmjt** [comment] 2016-06-09 09:01
https://www.dropbox.com/s/yzt52dy6v7ouskd/droidsounde16647_69.apk?dl=0
try this

**Comment by droidmjt** [comment] 2016-06-09 09:01
also try the noise sharpening function under volume settings

**Comment by filevans** [comment] 2016-06-09 22:35
Yes I always meant to ask for something like this, good work

**Comment by droidmjt** [comment] 2016-06-10 11:13
the dsroot thing can be tested by removing droidsound/dsroot folder and keeping the old dsroot, then running the app again, i think in _69 build it works as expected, i tested it few times.

**Comment by droidmjt** [comment] 2016-06-14 03:13
leave a comment if you test this more

**Closed by droidmjt** 2016-06-14 03:13 UTC

**Comment by Level99OCR** [comment] 2016-06-21 10:10
Sorry, I've been out of the country. Grabbing this and testing today.

**Comment by droidmjt** [comment] 2016-06-21 10:19
https://www.dropbox.com/s/oc9slejnqz3g5u7/droidsounde16647_72.apk?dl=0

that one has some NSFe related fixes and a font selector. I will add echo plugin now.

**Comment by droidmjt** [comment] 2016-06-21 10:21
I recommend you use some test phone for _72 just incase it messes up something.

**Comment by droidmjt** [comment] 2016-06-21 13:51
cancel the echo plugin :(

**Comment by filevans** [comment] 2016-06-27 14:23
there's still internet out of the country

**Comment by Level99OCR** [comment] 2016-06-27 18:50
filevans: I prefer to disconnect from the internet as much as possible while away these days, simply because I live life connected perpetually while at home doing my dayjobs :)

Tested with 72, seemed just fine, so thank you again for doing this. No issues with the merging from what I could tell. Going to go back to the "broken file types" sometime this week since the trip allowed me to test some new ones from VGMStream and there's quite a few that crash the app. More info later, thanks for the continued support.
