### ISSUE TITLE
Lockscreen controls. 

### ISSUE THREAD

**Issue by x-amp** [droidmjt/Droidsound#173] opened 2015-05-27 12:26 UTC
I recently updated to the Google Playstore version of Droidsound and for some odd reason, no matter what format I'm playing, using the lock screen controls have a massive delay. Sometimes they don't seem to work at all. When I revert to 1.662 the issues isn't there.

**Comment by droidmjt** [comment] 2015-05-27 13:49
what android version you use?

**Comment by droidmjt** [comment] 2015-05-27 14:22
also that 1662 version, is it beta or official version?

**Comment by x-amp** [comment] 2015-05-27 16:24
I believe it was beta.. I using a Samsung Galaxy S4 on android version 4.4.2

**Comment by droidmjt** [comment] 2015-05-31 12:51
https://www.dropbox.com/s/czqlcra25wxv1er/droidsound1663_nowidget.apk?dl=0

try, it has widget disabled + no psf reverb option, let me know how it works

**Comment by x-amp** [comment] 2015-05-31 14:26
Seems to work better. After a restart, there is a bit of a delay on the first time I try to move to the next track. After that its fine.

**Comment by droidmjt** [comment] 2015-06-01 23:27
all right, i'll make a new debug build soon, let's see if we can get this fixed

**Comment by x-amp** [comment] 2015-06-02 02:49
Are you able to duplicate the issue on your end? After a couple of day of use, the lock screen  controls have a hit and miss situation. The press is registered but the action is delayed. Weird thing is, the notification controls work flawlessly even while the phone is in the lockscreen

**Comment by droidmjt** [comment] 2015-06-04 05:09
i tried with 4.4.4 and was not able to reproduce the problem, i'll get back to this when i get back home

**Comment by droidmjt** [comment] 2015-06-05 03:25
sigh,now that i started fixing bugs again, i'll make a new binary today and lets see if it fixes the remaining problem.

**Comment by droidmjt** [comment] 2015-06-05 05:43
https://www.dropbox.com/s/1h137xlejy7d1uz/droidsounde1664_04.apk?dl=0

**Comment by x-amp** [comment] 2015-06-05 10:13
Looks like we have a winner. I'll play around with for most of the day and see if anything changes.

**Comment by droidmjt** [comment] 2015-06-06 07:25
good good, i hope it works finally

**Comment by x-amp** [comment] 2015-06-08 00:28
Seeing no problems. Think this one is solved

**Comment by droidmjt** [comment] 2015-06-08 00:57
excellent, i'll close this case.

**Closed by droidmjt** 2015-06-08 00:57 UTC
