### ISSUE TITLE
Another external SD path to add

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#208] opened 2015-11-01 02:19 UTC
Just picked up another tablet and the latest Play Store release is missing the external sd path. This one is located at the following:

/mnt/extsd

**Comment by droidmjt** [comment] 2015-11-01 06:05
I'll add it.

**Comment by droidmjt** [comment] 2015-11-01 11:33
https://www.dropbox.com/s/z1p38190qztoc59/droidsounde1664_77.apk?dl=0

**Comment by Level99OCR** [comment] 2015-11-02 16:03
Grabbing it after work today to confirm.

It seems like with the breadth and depth of Android devices available, this might be a good option to add for user to manually define their external sd path. Could have a list of commonly-used paths as well as the ability to put down a keyed in path, instead of needing to compile a new version every time another one is discovered.

**Comment by droidmjt** [comment] 2015-11-03 11:10
those that i have added now should be enough, but lets see

**Comment by droidmjt** [comment] 2015-11-07 06:38
is this working now?

**Comment by Level99OCR** [comment] 2015-11-13 00:41
It wasn't but it turns out the tablet was faulty, I just got the replacement in and indeed it is working now.

**Comment by Level99OCR** [comment] 2015-12-17 13:34
Trying out CM13 for Zenfone 2 and it has the stupidest path for external SD card I have ever seen. External SD is mounted to:
/storage/4A20-17EE

Yes. I know. It is bizarre. Any chance of getting a quickie add to the allowable storage paths list?

**Comment by droidmjt** [comment] 2015-12-17 17:08
ok i add it

**Comment by sketch242** [comment] 2015-12-17 17:14
Just wanted to point out, in case it's not obvious, that it looks like it's mounting the filesystem by name under /storage..  DOS filesystems are normally created with a name in the format of [4 hex digits]-[4 hex digits].  So if you reformat your SD card, it will probably have a new mountpoint.

**Comment by droidmjt** [comment] 2015-12-17 17:17
i'll add some sort of regular expression thingy there :)

**Comment by Level99OCR** [comment] 2015-12-17 17:36
Okay, thanks. Also the CM13 is not perfect, I had to reformat it from exfat to fat32 (exfat support on this custom rom is broken but works on stock), so it named it that when it formatted the card. CM13 official on Moto G LTE gen1 also has the same 4/4 naming scheme for external storage so it looks like it may be how marshmallow works. Though the name itself is different on that device.

If that's the case, may need to just allow listing of all directories under storage (unless that requires root). Otherwise, there may need to be an extra step added where the user can navigate using the phone's own file browser to the location of the external storage and set that parameter within droidsound correctly. Does that make sense? If not, I can show you an example with ES File Explorer as well as SMS Backup and Restore.

**Comment by sketch242** [comment] 2015-12-18 15:04
Just to be clear, the [4 hex digits]-[4 hex digits] is only the default name, you can set it to whatever you want (up to 11 characters in the case of FAT) at format time or later.  There's also probably no guarantee that the user will only be mounting FAT filesystems, other filesystems are going to have their own naming conventions/limitations.  You probably just want to add anything under /storage, as that sounds like a CM-specific place to mount external filesystems.

**Comment by Level99OCR** [comment] 2015-12-19 03:02
Oddly enough, it doesn't look like it's the naming convention. The micro sd that was formatted in android under marshmallow does not have a volume name when I put it in my computer. It's a blank name.  From what I've read, Android 6.0 does not have set mountpoints anymore in order to offer an external card to potentially function as internal storage. Because of this, even if its set to use external as portable storage, it doesn't set a static mountpoint to something like external_sd. It will randomly generate that 4hex-4hex based on the device name or serial number and mounts it when it is detected (it has done the same for fat32 and exfat so far, have not tried and ext3/4 yet).

The bottom line here is under Marshmallow all external storage is going to have these randomly generated paths under /storage/ for external access, and up until now MJT has been hard-coding the allowable paths for the filesystem into the application. Under a previous version about a year ago, I believe we were able to browse the entire contents of the device without needing root, but that is confusing for people who aren't power-users (understandably so).

I agree that, in addition to any of the current hardcoded paths, anything under /storage/ should be allowed. It may be other roms don't play by the 4hex-4hex rule, but they still are going to dynamically generate a path somehow. 

I've been playing with MM on three different devices and it is a complete pain to navigate external SD stuff right now because very few apps were ready for this big of a change.

**Comment by droidmjt** [comment] 2015-12-19 09:27
fixed

**Comment by Level99OCR** [comment] 2015-12-19 18:19
Wicked! That was super-fast. Will close this once I can test it on the MM devices, thanks as always!

**Comment by Level99OCR** [comment] 2015-12-23 14:26
Bumping this just to FYI: I'm out of internet contact from tomorrow through early Jan. Not sure when you planned to upload next build with all these fixes, but if you wanted testing on my part, I'd need to get my hands on APK before I leave. If not possible, no worries, I just can't close it until after I get back then. Happy holidays!

**Comment by droidmjt** [comment] 2015-12-23 15:31
new version will be uploaded within next 8 hours

**Comment by droidmjt** [comment] 2015-12-23 22:54
https://www.dropbox.com/s/u1ythy8f5nnob7z/droidsounde16647_10.apk?dl=0

**Comment by crimson1117** [comment] 2015-12-24 11:24
ah,my samsung galaxy enter app and crash,I deleted sdcard/droidsound and still crash:(

**Comment by droidmjt** [comment] 2015-12-25 09:55
reopen this case if the problem is still there or at least leave a comment, i'll close this

**Closed by droidmjt** 2015-12-25 09:55 UTC

**Comment by Level99OCR** [comment] 2016-01-02 16:47
This worked perfectly, thanks again for implementing it! Simultaneously able to report bugs on CM13 now while not having to sacrifice listening to video game music :)
