### ISSUE TITLE
vgmstream plugin crashes when loading Amiga files :(

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#305] opened 2016-07-13 03:40 UTC
Nexus 5x, CM13 6.0.1, DSE v83 (latest).

I uncheck all the plugins I don't use (Amiga, trackers, MODs, etc.). Then whenever I try to open an unsupported file, DSE crashes.

Should you try to handle it more gracefully?

**Comment by droidmjt** [comment] 2016-07-13 03:42
no lets leave it like that

**Comment by jimbo1qaz** [comment] 2016-07-13 03:47
Any benefits?

**Comment by droidmjt** [comment] 2016-07-13 03:48
I just disabled all the plugins, restart the app, enabled 1 plugin (openmpt) and tried playing something that it shouldn't play, and no crash.

**Comment by jimbo1qaz** [comment] 2016-07-13 03:49
I tried Examples/Amiga/#reload, and it crashed.

**Comment by droidmjt** [comment] 2016-07-13 03:54
tried wit emulator and real device, can't make it crash, I need logcat of the crash, or see if it produced a log file in droidsound/crashlog about it.

No benefits and it is useless to ask things like that, if something crashes the app, don't you think it would logical to get it fixed?

**Comment by Level99OCR** [comment] 2016-07-13 11:44
jimbo1qaz, for the latest version of Droidsound that you're running, did you do a clean install or a dirty upgrade? The reason I ask is that I also had a false-positive bug upgrading from build 81 to 83 where the TXT file handling was fixed but for some reason I was getting crashes trying to play some songs. If you did a dirty upgrade, can you uninstall the app, remove the pertinent directories (DSEMusic, dsroot, droidsound, etc.) and try installing build 83 fresh and seeing if it still happens?

**Comment by jimbo1qaz** [comment] 2016-07-13 16:38
Woops, I think the big only shows up on Amiga files. (at least, all other Examples/ don't crash)

**Comment by droidmjt** [comment] 2016-07-13 17:15
This is what I did: removed all the DSE folders, fresh install of _83, start the app, disable plugins except openmpt, restart the app and played Examples/Amiga files, only MOD files played, others got skipped. If it produces a crash, logcat is the only way.

**Comment by droidmjt** [comment] 2016-07-16 04:42
If no logcat log, close this case, I cannot reproduce the problem anyhow.

**Comment by jimbo1qaz** [comment] 2016-07-17 23:36
Looks like a vgmstream library bug. I've encountered similar issues before when renaming file extensions under foobar2000.

http://hastebin.com/raw/uducakebaz

**Comment by droidmjt** [comment] 2016-07-18 03:49
I encountered this bug before, what plugins you have disabled?

**Comment by jimbo1qaz** [comment] 2016-07-18 03:53
I posted a link on the HCS forums (vgmstream developer?) https://hcs64.com/mboard/forum.php?showthread=46169

Disabled:
asap
adlib
basszxtune
highly theoretical
hively
kss
klystrack
mdx plugin 2
mdx
nez
netradio
openmpt
organya
pmd
s98
stsound
sidplay2fp
uade
wonderswan

(This list is approximate. I think all that matters is the right plugin is disabled, and it falls through to vgmstream. Does disabling plugins reduce memory usage?)

**Comment by droidmjt** [comment] 2016-07-18 04:16
The only reason this enable/disable plugins feature exists is that on Android 4.2 and earlier there was a hard limit (128) for loaded shared libraries. Yeah, disabling plugins reduces memory, but they all take about 32MB of memory so I don't see that a big problem :)

The problem with the format is that amiga and vgmstream share the same file extension (AHX), for some reason vgmstream manages to load it but playing fails -> crash happens. I'll investigate this later today. I just tighten some file checks.

**Comment by droidmjt** [comment] 2016-07-18 04:27
https://www.dropbox.com/s/kwdnrmub2bdjum7/droidsounde16647_88.apk?dl=0

**Comment by droidmjt** [comment] 2016-07-18 04:35
shit, it still crashes, quickfix didn't work, I fix it later today.

**Comment by droidmjt** [comment] 2016-07-18 04:44
https://www.dropbox.com/s/jctko3rfnaxam5b/droidsounde16647_89.apk?dl=0
this works, tested with debugger :)

**Comment by jimbo1qaz** [comment] 2016-07-18 04:47
yeah my old Galaxy Nexus had only 768 MB of memory, I discovered that
disabling plugins would let me run more apps together.
However, my Nexus 5X has 2GB of RAM. Removing 32MB won't help much, in
comparison with my other heavyweight apps.

**Comment by kode54** [comment] 2016-07-18 05:23
It appears the vgmstream plug-in is attempting to call reset_vgmstream on a null pointer?

**Comment by droidmjt** [comment] 2016-07-18 05:46
its the glue code of mine that is missing some checks, anyway, it should work now, with _89 build

**Closed** 2016-07-18 05:55 UTC
