### ISSUE TITLE
Hang on startup

### ISSUE THREAD

**Issue by sketch242** [droidmjt/Droidsound#180] opened 2015-07-14 21:38 UTC
I've seen this happen occasionally before, but even after cleaing cache, etc, it seems to be much worse than before with the most recent release version on my Nexus 5.  I often have to restart DroidSound 4 or 5 times before it succesfully starts.  

The only recent change I've made is switching to a new phone, I copied exactly the same music library over. I never had problems like this with my old phone (a GPE-converted HTC One m7).  I'm not certain it happened right away with the new phone though, I think it was not until the latest release of DSE.  Any suggestions for how I can help troubleshoot this?

**Comment by droidmjt** [comment] 2015-07-15 04:07
with the new phone, try without any playlists and filebrowsers. remove/rename all filebrowsers objects in dsroot folder, then restart the app, this is most likely caused by playlists or music data.

**Comment by sketch242** [comment] 2015-07-15 13:15
I initially thought the playlist file was the problem, as I noticed there was a change in format between old and new entries (I've been using the same playlist since the oiriginal Droidsound before you forked it).  When I first tried it, it would almost always crash. Then I deleted the playlist, and it worked.  But DSE recreates the playlist after the first run from somewhere (database?).

**Comment by droidmjt** [comment] 2015-07-15 14:45
are you using the version from GP or the latest unofficial release?

**Comment by droidmjt** [comment] 2015-07-31 05:48
https://www.dropbox.com/s/8h53xv1mi60ax3r/droidsounde1664_33.apk?dl=0
try this version if you still have problems

**Comment by droidmjt** [comment] 2015-07-31 16:00
i'll close this case due to inactivity, feel free to reopen it if the problem exists

**Comment by sketch242** [comment] 2015-08-05 15:47
Sorry about that, missed the messages about this.  I did some more testing and it actually seems to not crash anymore, it just hangs for upwards of a minute every time I start droidsound.  I haven't tried the new build yet, but I will check it out.

**Comment by droidmjt** [comment] 2015-08-05 16:10
sounds like playlist related problem

**Comment by droidmjt** [comment] 2015-08-27 07:45
https://www.dropbox.com/s/qcbef1xvqrin627/droidsounde1664_40.apk?dl=0
I'll close this again, reopen if none of these new versions work.

**Closed by droidmjt** 2015-08-27 07:45 UTC

**Comment by droidmjt** [comment] 2015-09-09 18:07
I noticed one thing about this, if you have lots of files (>1000) under fileCache folder, it will take quite some time to get started, empty the cache and it should speed up.

**Comment by sketch242** [comment] 2015-09-09 20:24
You may be onto something.  I just cleared filecache, restarted, and it restarted almost instantly.  Closed and restarted again, and it took about 2 seconds.  A lot better than the 2 minutes I usually see.  

Is the filecache used for any files that are uncompressed from zip for playing?  Or does it uncompress entire zips at a time?  I've been going thru a large archive of atari chiptunes, which isn't that big overall (14MB), but contains a lot of files (nearly 5000).  BTW, I already have 'filecache size in MB' set to the smallest option, 32MB., unless -1 means none.

I'll check out the new version too...keep forgetting to upload that to my phone and test it.

**Comment by droidmjt** [comment] 2015-09-09 20:37
-1 means unlimited space (not recommended, only for the crazy), the latest version is not available yet, i'll upload it tomorrow, I've been very busy recently.

fileCache is used for files when you download something from modland or play something from archives, a temporary space. When you want to play something from an archive, it extracts only the wanted file to filecache and then plays it from there.

What comes to filecache, it's all about file and subfolder count.

**Comment by droidmjt** [comment] 2015-09-09 20:42
https://www.dropbox.com/s/b8vilo8cz9ksvci/droidsounde1664_50.apk?dl=0

here is the latest, but be careful, there may be bugs :)

i'm currently using the same build to test stuff.

**Comment by sketch242** [comment] 2015-10-14 20:21
Just wanted to note that I've been using this version or newer for over a month since I last cleared the cache and I haven't seen any slowness at startup.
