### ISSUE TITLE
Title of Subtunes Were Invisible if File Title Was Too Long

### ISSUE THREAD

**Issue by wmjordan** [droidmjt/Droidsound#487] opened 2019-06-06 06:11 UTC
[Might & Magic- Secret of the Inner Sanctum.zip](https://github.com/droidmjt/Droidsound/files/3260199/Might.Magic-.Secret.of.the.Inner.Sanctum.zip)

The above file has a long title.
The titles for subtunes were invisible.

Is it possible to word-wrap the title part?

**Comment by droidmjt** [comment] 2019-06-06 13:15
no need to wrap, download the latest version (build 164)

**Comment by droidmjt** [comment] 2019-06-07 05:08
I'll close this issue since the problem is fixed. You should see the scrolling title since build 164.

**Closed by droidmjt** 2019-06-07 05:08 UTC

**Comment by wmjordan** [comment] 2019-06-17 00:30
Thank you for addressing this issue.
Unfortunately I could not access dropbox in my country. I will attempt to download your release later. If you could upload your releases on GitHub, that will be much obliged.

**Comment by droidmjt** [comment] 2019-06-22 10:51
Sorry, I won't be uploading any APK files here, you need to find a way how to get them from Dropbox.
