### ISSUE TITLE
Feature Request: option for volume equalization

### ISSUE THREAD

**Issue by dominater01** [droidmjt/Droidsound#117] opened 2014-08-19 23:47 UTC
Can you make an option that will make all songs play at the same volume?

**Comment by jimbo1qaz** [comment] 2016-06-27 01:02
Is it possible to load ReplayGain tags created on the desktop (foobar2000)? Right now, I have a soundtrack with 3 recorded songs, which are far louder than the psf tracks.

Also, different games have different volumes.

**Comment by droidmjt** [comment] 2016-06-27 01:03
if you give me few example songs, I can try to add this feature.

**Comment by jimbo1qaz** [comment] 2016-06-27 01:27
Do you know the websites of game emu player, PSF decoder, mp3/aac/ogg libraries? Their existing code *may* already include ReplayGain reading.

Also, you can analyze files, or test your code on them.

do you want a few files, or entire soundtracks worth?

**Comment by droidmjt** [comment] 2016-06-27 01:31
yeah I have those, I just need some exampe songs.  3-5 urls to files that contain replaygain info would be enough i think.

**Comment by jimbo1qaz** [comment] 2016-06-27 05:20
Here is a selection of files: <https://dl.dropboxusercontent.com/u/34131225/replaygain.7z>

Note that there are two types of replaygain: file and album. file replaygain is always present, but album is not.

foobar2000 allows the user to choose between no RG, file-only replaygain, or album (fallback to file). 

Additionally, it allows the user to apply gain, prevent clipping according to peak, or both.

**Comment by droidmjt** [comment] 2016-06-27 05:33
This is scary, you included a song that I was already viewing before I downloaded your 7z file ( the chrono cross song).

**Comment by jimbo1qaz** [comment] 2016-06-27 05:38
none of them had replaygain beforehand. I added them all in foobar2000.

I haven't confirmed that RG tags are identical between different taggers. I
suspect unconventional (game/tracker) formats may have more variation. One
time, I edited the metadata description of one PSF file in foobar2000, and
the title/etc. wouldn't show up in Audacious.

But you're reading tags only, which may be less problematic.

**Comment by droidmjt** [comment] 2016-06-27 05:55
i meant that I already had a chrono cross song with the replaygain tags, the sha1 is a bit different than the file you gave

**Comment by jimbo1qaz** [comment] 2016-06-27 05:57
yeah, that's because I added them myself. the formula is likely different,
based on which psf you start with, which psf plugin was used to calculate
the volume, and which tracks you selected for the album.

are you talking about the "Examples" song? that's how I discovered the
chrono cross soundtrack ;)

**Comment by droidmjt** [comment] 2016-06-27 05:58
102 The Brink of Death.psf thats the song I was viewing

**Comment by droidmjt** [comment] 2016-06-27 05:58
but nevermind, its just funny coincedence

**Comment by jimbo1qaz** [comment] 2016-06-28 16:59
(Suggestion) Would a speaker icon be more intuitive than a mixer icon, for the volume panel? Would it be more intuitive if the volume panel included ReplayGain settings?

**Comment by droidmjt** [comment] 2016-06-29 00:36
I can change the icon no problem. I'll see if i can fit the RG settings in volume panel.

**Comment by jimbo1qaz** [comment] 2016-06-29 00:45
I (myself) only adjust ReplayGain occasionally (less than audio plugin settings), rather just "turn on and forget". So does it need a menu icon?

What do you think?

**Comment by droidmjt** [comment] 2016-06-30 03:36
https://www.dropbox.com/s/wofugue4x25u405/droidsounde16647_77.apk?dl=0

as usual, report old/new bugs

**Comment by jimbo1qaz** [comment] 2016-06-30 05:43
I open the options panel, the checkbox is there, but I can't check it (even
when playing a tagged PSF file).

**Comment by droidmjt** [comment] 2016-06-30 05:46
its just indicator that RG info is in use, you cannot change it.

**Comment by droidmjt** [comment] 2016-06-30 06:28
it works so that, when you enable RG stuff from Settings, if a song doesn't have any RG info, the indicator in volume settings doesn't get activated and common volume settings are available. If RG info is available, the indicator gets activated and common volume settings gets disabled.

**Comment by jimbo1qaz** [comment] 2016-06-30 06:36
So you added a new RG menu entry, with a checkbox indicator in the volume
menu.

My bad. Would "Current RG volume status" be more clear that it's an
indicator rather than a toggle?

(I couldn't find any native Android indicator widgets. A circular light
image with green or black/red center? That may not be the best idea, since
it doesn't look native.)

**Comment by droidmjt** [comment] 2016-06-30 06:59
how about green/red radio button, at least its better than checkbox

**Comment by jimbo1qaz** [comment] 2016-07-01 04:23
Right now the RG indicator shows whether or not the menu entry is enabled. I tried opening files where RG data is missing, and the checkbox is still checked. Is that intentional?

Do you think making RG-vs-plugin a radio button, then adding a shortcut in the volume menu leading to the RG settings is a good idea?

**Comment by droidmjt** [comment] 2016-07-01 05:26
the latest version has a radiobutton followed by status text, the status text says what RG info it is currently using

**Comment by droidmjt** [comment] 2016-07-01 07:12
https://www.dropbox.com/s/ahu4tlavb2elj1q/droidsounde16647_78.apk?dl=0
i hope at least some bugs got fixed

**Comment by jimbo1qaz** [comment] 2016-07-01 19:24
Seems good?

**Comment by droidmjt** [comment] 2016-07-02 00:44
yeah the current is good

**Comment by jimbo1qaz** [comment] 2016-07-02 17:10
Did I just hit Reset RG and unrecoverably lose ALL my RG tags?

**Comment by jimbo1qaz** [comment] 2016-07-02 17:25
Well,  I did a full rescan, closed and reopened the app, and RG seems to be back.

Is full rescan needed, or just quick?

**Comment by droidmjt** [comment] 2016-07-03 01:10
I wouldn't worry too much about the RG info being in the DB or not, you don't need to perform any scanning to get the RG infos. They are being collected while you play a song and then stored and next time when a same song is being played, the  metadata scan is skipped and RG info is retrieved from the DB.

**Comment by droidmjt** [comment] 2016-07-04 05:20
I suppose it works, I'll close this case

**Closed by droidmjt** 2016-07-04 05:20 UTC
